
=== Title: Alien Conversations - Notes

=== Date: June 9th, 2018

----

Note: Questions were openly asked in chat room and any alien from any dimension was open to step forward and speak.  Sometimes specific aliens where asked questions when someone knew there name or someone asked for there name.

----

1. Meditation / Light Energy 

2. The Great Destiny - the Greatest Achievement is to join the Prime Creator.

3. New Earth + New Life

4. You connect with his [ God's ] Love.

5. Keep working on the light; care about the planet.  

6. Government won't listen or accept assistance.

7. We want to save the earth; We need everyone to work on saving the earth.  If you can do that the ascension will happen.

8. We must come together and change how where doing things before it's too late.

9. Take care of mother earth.  You can't continue with wars and nuclear weapons; They won't allow it.

10. They Need to start listening.

11. We tried to give your government technology to assist.  They refused.

12. It's up to you to end your suffering.  Where here to assist you in saving yourself.

13. If all the people of earth would allow us to assist we would assist at that time.

                                         *- Brihasee, Elohim*



----

Note: Confusion between Blue Avians and Grays)

----

1. Blue Avians - Are here to assist and teach

2. Grays are workers to gather information, to do testing to make sure evolution is going according to plan.

3. There are other races that protect the planet from other entities that mean you harm.

4. [ What can we learn from you? ... ]

5. * Technologies for _*water purification*_, _*for energies*_, _*for advancements*_, _*for improving the soul*_, _*pollution*_.

                                         *- Name Unknown, Gray*


1. STOP doing what your doing!...

2. STOP the Wars!

3. STOP the Fighting!

4. Your not that all powerful; you will destroy everything!

                                   
																	        *- Ardif*


----

Note: Question on the wave or the shift in energy was asked.

----

1. It will affect _*all beings*_, _*the planet*_, and _*the solar system*_.

2. [ How will everything be affected? ]

3. The pulling in of energies...

4. Energies will start making the changes in reality and a dimensional shift will occur.

5. Energies will fill everything and everyone until it happens.

6. It is not a wave that happens instantly; A slow pulling in of energies.

7. So it's coming to a completion- you didn't feel it before.


                                          *- Name Unknown, Alien Unknown*


----

Note: Asked what crystals can help heal humans?

----

1. A blue type crystal...

2. "Assisting with bodies energies"

3. "They see everybody and watch everybody."   


                                           *- The City of Atlantis Collective*



1. Assisting with the evolution and DNA rearranging

2. You attain and collect knowledge more efficiently with increase in Light

3. You have to handle this increase in knowledge so DNA must be restructured or rewired.

----

When will ascension happening human years?

----

4. Depends on the people developing and sharing the light.

5. Energy is building and building.

6. Your body will transform and evolve.

                                        *- Anunnaki*


----

Note: Genetic altering was to be harmful; some aliens are trouble makers

Question was asked to try to see what evil is and if it didn't exist really...

----

1. Evil is a name. *Action*

2. Evil is addiction

3. Negative Energies


----

Note:  Some beings appear to be given special missions.

----


_*Final Comments:*_

1. We are seeing matching principles coming from throughout the universe.  

2. The principles are consistent and matching from various locations like: Edgar Cayce, Course In Miracles, Aliens, and in other leading religious beliefs.

3. The message is:

* Raise your consciousness, 

* Increase your Light Energy, 

* Practice Love, Forgiveness, and Peace to All Beings,

* Stop Wars, Stop Nuclear Wars, Stop Fighting.

4. These are the *Principles* that seem to be key to 8human advancement* and the *evolving of the world, and universe.*








.
.
.
.


















