

=== Brain power - Improve Your Mind as you age

=== By Michael J. Gelb and Kelly Howell

=== Chapter 1: Think counterclockwise
“In the first century BCE, the Roman philosopher Seneca realized that he could change our lives by changing our beliefs; he advised that the process of aging “abounds with pleasure if you know how to use it.”  Bring more pleasure, fulfillment, and exhilaration to your life by using these proven techniques to improve your mind at any age.”

Expectations determine outcomes.  If you expect your mental and physical capacity to diminish with age, it probably will.  If you have the expectation that you will grow younger and live longer, this will be your experience. - Deepak Chopra.  

No pessimist ever discovered the secret of the stars, or sailed to an uncharted land, or opened a new doorway for the human spirit. - Helen Keller.

Pessimism leads to weakness, optimism to power. - William James

In the central place of every heart there is a recording chamber.  So long as it receives a message of beauty, hope, cheer, and courage - so long are you young.  When the wires are all down and your heart is covered with snow of pessimism and the ice of cynicism, then, and only then, are you grown old. - General Douglas Macarthur.


An unquestioned mind is the world of suffering. - Byron kate

Katie suggests that, after you have investigated your statement with the four questions, you aim to experience the opposite of your original statement.  She calls this a “turnaround.”…

You might turn around the original statement (‘m I’m always forgetting things; my memory sis getting worst with age” by stating, “I always remember important things.  My ability to remember what’s important is improving with age.”….

As you learn to turn around your negative, pessimistic thought patterns, you’ll feel better and respond to life’s challenges in a more adaptive and creative manner.


GFH three essential practices that improve mental acuity and extend your life:  
- _*gratitude*_,
- _*forgiveness*_, 
- _*and humor*_.

“He is a wise man who does not grieve for the things whihch he has not, but rejoices for those which he has.” - Epictetus, Greek philosopher

Life is an adventure in forgiveness. - Norman Cousins

“When I was young I was called a rugged individualist.  When I was in my fifties, I was considered eceentric.  Here I am doing and saying the same things I did then and I’m labeled senile. - George Burns, in the film just you and me, kid.

“Words are, of course, themost powerful drug used by mankind.” - Rudyard Kipling.

Old peope are seen as:
Sages
The Wise
Elders
Seers
Patriarchs/Matriarchs



=== Create a Brain-Enhancing Environment

“A man should hear a little music, read a little poetry, and see a fine picture every day of his life, in order that worldly cares may not obliterate the sense of the beautiful that God has implanted in the human soul. - Johann Wolfgang Von Goethe

“I think you might dispense with half your doctors if you would only consult Dr. Sun more.” - Hentry Ward Beecher.

“come forth into the light of things, Let Nature be your teacher” - William Wordsworth

“If one way be better than another, you may be sure it is nature’s way” - Aristotle

“Those who love deeply never grow old;  they may die of old age, but they die young.  - Benjamin Franklin

Brain Rule #9 = In his book Brain Rules - John Medina - says a multisensory environment improves memory and learning ability.  Those in multisensory environments always do better than those in unisensory environments.  They have more recall with better resolution that lasts longer, evident eventy twenty years later.

