=== Coming Home to Lemuria II

Out of Ego and Into Oneness
1. Move out Ego. 
2. Clear painful memories of The Fall because we are associating the process of manifestation with pain of the Fall.
3. We lost many of our DNA strands and fell into a great void- into another consiousness.
4. Now we can consciously reclaim our innocence.
5. Now is the time for consummation of the whole process, the combination of consciousenss and innocence fusing into One.


1. In the womb of the Great Mother, we came into matter.  
2. The Fall was the great moment when we brought Light into this matter as a way fo the creation of duality with Divine Father and Divine Mother coming together as One in the act of Creation.
3. Time to step forward and claim this power and our mastery over all the dimensions.
4. We must claim the Light as we bring the male principle back into balance with the female principle.  
5. we created our world, the flowers, the plants, and the creatures in the Temples of Creation.
6. We have knowledge and power encoded in our DNA.  
7. It is now time to release these memories, reactivate the codes, and return Mother Earth to Paradise, the Garden of Eden.



Hawaii And the Pacific Islands
1. Certain places on earth are holding memories of Ancient Lemuria, and people are being called there…. they hold the frequencies of the lost civilization.
2. New Zealand, Australia, Indonesia, Japan, Pacific Islands.. stored in stones and land…
3. West coast of North and South America, California, Brazil, Chile, Mexico, and Peru.
4. Dolphins and whales who are waiting to reconnect with us and help us to wake up and remember who we are.


1. hawaiian Islands are a generating point that is connected to all the Pacific islands. 
2. We brought the codes in here and put them into a form in which they culd travel through the key lines of earth grids.
3. We translated them sothat they could be received on the earth plane.  
4. Many Lemurian masters are being called to return toHawaii to have thier dormant codes activated.
5. Nothing is ever lost.  not something we need to learn, just remember. 
6. These codes can be activated by sound, by interaction with whales an dolphins in any manner, or by healers who hold the frequencies.
7. Big island of Hawaii has ore energy of Lemuria after The Fall.
8. Pure vibrations that existed befoer the Fall are more at Maui, Lanai, Kauai.  … more refined energy here so it is easier to bring in the blueprints for The Wholeness Matrix.
9. More Lightworkers on Maui cause u don’t need to refine the enegies there… unlike BIg Island of Hawaii.
10. The underlying grid is already in place to anchor the blueprint of Wholeness.  It is strong, easy to access and work with.
11. the Haleakala volcano there was a very poweful energy center in Lemuria.
12. This energy makes the Lemurian frequency more easily accessible for the teachers, healers, and leaders of the New Dawn upon the Earth.
13. To bring back the ancient teachings and truth.
14. As we reconnect to Source and become whole and healed, the energy reverberates like ripples on a pond and touches many more.
15. When we are in the wate rwith the cetaceans hearing their sounds or just seeing them, we can easily receive the codes that will help us remember Wholeness and Love.
16. When enough people remember, the whole planet can returnt o the Lemurian consciousness of pure Love and Wholeness, but this time it will be in our dense physical bodies.  
17. When the frequency of unconditional Love is resonating in our enegy fields, it will affect and activate the energies of anyone who comes into contact with us.



Ceremony to Re-open the Grid of the Crystal Cit in Kaelekakua bay
1. Toning to reopen the grid of the crystal city.
2. It is out in the ocean between Kealakekua Bay and Honaunau bay… bays where the dolphins are most active.
3. Toning int he energy of the sun with intention of reconnecting with the frequency fo Wholeenss through the Great Central Sun.
4. The City of Light
5. Completed the re-activationo f the temple.  
6. Crystal cities on Haleakala, Kalalau Valley on Kauai, Manele Bay on Lanai, and Huelo on Maui.  
7. Those of have reconnected with these ferquencies have the energy of the New Earth already resonating in their fields. 
8. The energy shift is beginning in Hawaii, and from there it is traveling out across the Earth.  
9. The lightworkers carry this eenrgy in there energy field. 
10. After spending five months on Hawaii receiving activations, I then found myself traveling for six months carrying the frequencies to ENgland.. .. to Stonehenge and Glastonbury, then to cali: New Grange in Ireland, Salt Lake City….. 
11. Just by traveling u are walking the light into being.
12. The Lemurian Temple
13. Toning is especially powerful to transmit the codes as the sound is received by the rocks and the crystals at the sacred sites and by everyone who subsequently visits there.
14. I always tone and then go into silence to see what message the stones have for me.
15. Ceremony, prayers, toning or sitting in silence will help to connect with memories of the place.  
16. As we hold the Blueprint fo rthe healed, transformed Earth, she is slowly moving into that energy; 
17. We are growing a new body of LIght and so is Mother Earth.
18. Charmian
19. back to Whoeleness and Back to Love
20. it is time now to activate the light codes in the DNA that were downloaded in Lemuria.
21. These codes will help us to activate our Divine Human-Galactic Light Body and allow us to create a new reality, which could manifest as successful reelationships, financial abundance, or a beautiful home.  Charmian helps us activate codes and mmagnetize our Soul Kin to us…… bringing back that feeling of community….   doula and hypnobabies instructor.
22. We can now return to the way society was organized and operating in Lemuria…. The ancient Lemurian connection is still here although many people don’t think about it now.
23. Being on Maui is home to Charmian.
24. she was a grid master in lumeria.  she held the master key.
25. Open up energy fields through singing, drumming, toning or journeying so people can receive whatever they need.
