
=== Coming Home to Lemuria
=== By By Charmian Amarea Kumara Redwood 



=== Lemurian Consciousness
1. Life in Lemuria was a marriage of God and man, the physical awareness of the body, the self, and the Bliss/Oneness of Beingness with no separation between God consciousness and self.  In order to speak from this place of selflessness, we would need a new language for we can only talk about it now in bits and pieces.  It’s like nothing people can imagine today.
2. Everything we did in Lemuria was circular.  Our subtle light bodies were globes of light, and we worked in circles within circles.  We could extend our energies so that we were always connected to the others in our circle.  We were huge beings, so we could be physically very distant but feel we were close together.  We merged with each other in our subtle bodies.  Each circle emerged from our core and connected with the others in our team.  Also, everything around us vibrated with color and sound.  We held the consciousness: I am one with everything.  I know everything, and I can manifest anything.


=== The Universal Eye Unites with the Heart Chakra
1. In our teams we connected through our third eyes and brought the energy nito our hearts.  We had a saying, “I see the Eye and the Eye sees me.”  The Eye put into our consciousness the vast knowing that we could do everything, and we were everything.  Nothing was ever in doubt or question; everything was a “yes.”
2. That was the purpose of the Eye- to connect with the purpose of Oneness and focus our mutual goal.  We worked in our circles because of the Eye, and at the same time the Eye was here because we were anchoring it- each one of us individually and all of us together.  We had conscious Oneness with the Eye and could distribute our abilities to any parts of our bodies.  We stretched our arms and felt connected to the whole circle.  When we brought in our arms, then we used our eyes to see where the others were.  We connected to the Universal Eye through our third eye, our higher eye, and in the center of the circle was a connecting eye.  We reached out to each other and used that connection to manifest everything we wanted to create.
3. We connected in the heart with an intention we shared with the collective eye.  In this way we shared it with each other.  It spread and established very quickly, so we knew that everyone had the same intention.  We saw the intention with the third eye, brought it into our hearts and from there, we spread it through our arms, connecting with each other. We used sound to assist in the process of manifesting the intention.  We condensed our breathing, breathing sound through the mouths and also tuning in to the appropriate color for that we were manifesting.
4. We visualized what we wanted to create, and then we breathed into that image.  We held the image in the center of the circle at the level of the third eye.  The more we breathed sound from our throats, the more the image gained tangible density, form, and shape.  We used lines of energy to form patterns, which created the basic structure or matrix around which we wove the form and shape.


=== Focused Intent
1. We never had to think about “how” to do anything.  We just did it from our hearts, focused with intent and joy- so much joy and bliss.  We were constantly moving and vibrating.  In the early days of Lemuria, we were particles of light and energy, constantly moving and exchanging information with each other.  We would hold our focused intent on the vision.  When we held the vision, it was comforting to know that we didn’t hold it by ourselves.  There was always a circle of others beings of Light.
2. Other beings were available who knew how to anchor energy with focused intent.  We stood in our circle with others and held the image of what we wanted to create in the center of the circle.  When it was easy and anchored, we knew it was the right intent because the right use was supported by every part of ourselves.  What on present day Earth is now called ego, personality, or all the different fragments that have names were working together in alignment with the Whole.  Not one of them was left out or denied because each aspect of our Being contributed its own color or frequency to assist with the focused intent.  Before we wanted to to create anything, it was very important to recreate a sense of Oneness.
3. Everybody in Lemuria was in a place of absolute trust and could work together seamlessly.  Even though we were in separate bodies, we had a complete connection to Spirit and God and everything around us. Everyone was completely connected in an amazing awareness that God or the Divine was in every being.  We radiated that awareness.  It was like a geode with little crystals- each a crystal separate and yet part of the whole.  It was so peaceful and yet a dynamic whirling of energy and creativity.  There was so much Light.


=== From the Crown Chakra to the Sacral Chakra
1. In time we knew that it was time to bring the energies and frequencies past the crown, third eye, and heart.  Thus, we joined together in our creation circles and wove together the energy of our crown chakras with the continuity of life a major focus of our creations.  We had learned to create by focusing on the third eye and heart chakras: it was time to go further and connect to the lower chakras: it was time to go further and connect to the lower chakras in the energy system- initially with our second chakras where we brought in and held the highest vibrating energy- that of creation.  Thus, in order to form a harmonious creation, each member of the circle needed to be aligned in the crown, heart and sacral chakras.  Then the creation was aligned.
2. Whatever we wanted to create together had to have a masculine and feminine aspect in order to uphold the balance of life  As we function now in a fully activated physical body, everything we create also has a body, but then in our light bodies where everything was one, it was different.  We needed to acknowledge the mental and physical aspects and their vital connection to the overall purpose.


=== The Biggest Challenge- the Root Chakra
1. Then came our biggest challenge- to bring that high vibration into the root chakra.  That was a long process of evolution.  It took eons for us to develop that ability.  We felt so much more at ease when we just connected in our hearts, and we were in bliss when we onnected through the Eye and with the extensions of ourselves.  It required conscious, difficult “densification” to bring the energy all the way down to the root chakra.
2. The sound changed when it went down below the heart.  It felt grating, and we had to become comfortable with that.
3. Later chapters will reveal more informatino about the creation circles, but let’s learn a bit more from the regressions abou teh ancient Lemurians’ voyage to our planet, Earth.


=== The Lemurians’ Journey To Earth
1. As ancient Lemurians, we first came to Earth as fluid Beings of Light who could assume any body shape or form.  Everything in our society was created from liquid Light.   We came from the Source as Golden Light filtered through the Great Central Sun where we created form as Elohim or Lords of LIght.  The energy from the Great Central Sun was filtered again through the star systems.  As highly evolved Beings of Light who had traveled byond the Light, we were able to move through dimensions easily like we do now in our human form as we fly through the air in airplanes/gliders/jet/rockets/, hang gliders, etc.  We carried our consciousness to many different star systems, including Andromeda, Arcturus, Pleiades, Alpha, Centuri, Orion, and also Venus, as we collected skills and knowledge from each system to use on Earth.
2. From Andromeda, we learned much about the technologies of creating energy from sound and light and the higher frequencies of mathematics and sacred geometry which underlie all the structures we created in Lemuria.  We learned to transport ourselves through time and space by building light ships.
3. On Arcturus, we learned more about the use of color and sound for healing and energy balancing.  There are many Arcturian ships around the earth at this time constantly monitoring and balancing the earth’s energies, which are being disrupted by human unconsciousness.  
4. On the Pleiades, we also learned more about the technologies of combining light with crystals- how to harness and focus light and to use it for manifestation and teleportation.
5. On Sirius, the home of the Temple of the Eternal Flame, the Christ Light that holds the frequencies of Immortality, we learned that the consciousness of the Cosmic Christ was being seeded on the Earth at that time and has continued to present- and the future probably.  many of us came directly from Sirius to Earth with our friends, the dolphins and whales.
6. On Alpha Centauri, we found a very innocent and pure energy and learned to bring Pure Love into form.  This energy from the fifth dimension and above was very difficult to maintain in our descent into third dimensional density, but we all have the codes for it in our DNA.
7. It wasn’t a question of some of us being from the Pleiades and otherss from Sirius.  We had all been on each of the star systems at different times, and some of us have a stronger affinity with one system than another.  We traveled through all the systems in our galaxy on the way from the Great Central Sun to Mother earth.  We collected all the knowledge that we would need for our earthly life experiment   that knowledge is encoded in our DNA and available to use once our Light Codes have been activated.
8. Some of us came through the middle star in the belt of Orion.  It is a portal to another universe that vibreates at a higher frequency that Earth.  The portal’s opening begins with the blue white light of the fifth dimension where all is Oneness.
9. In the beginning we were Beings of Pure White Light.  We assumed the colors and frequencies of the many dimensional planes and frequencies through whih we traveled.  All of those memories have been dormant in our DNA and are waiting to be activated.
10. Our point of entry into this solar system on our way to Earth was through Venus’s geometric crystalline light portal.  This was a landing stage for all the different groups, including Cetaceans, to congregate from all the other star systems.  We spent a long time in love vibrations of Venus where we worked with our etheric bodies in the many Temples of Love. Many of us are unaware that we are still working in the dimensional temples there in our astral bodies during our dream states.
11. On Venus, we brought together all of the knowledge we had learned form the other star systems and harmonized it with Pure Love, the vibration of Venus.  The whales helped us do this and are waiting now to help us to remember that we are Love.


=== A Galactic Pulsation

In the very beginning, we were a galactic pulsation, a point of galactic power.  In groups we used creative techniques of comining color, form, and beauty.  The galactic power point created a physical body around it.  It created everything, including its own physicality.  It was a soul choice to bring the Light into the third dimension.

We brought the Light into the physical, and now we are bringing the physical back to the Light.  This was our choice for our soul’s growth.  We knew the Light, but we didn’t know if we could bring it into density and still be Light, and so we traveled through the star systems gathering great knowing on our way to Earth.


=== Crystal Cities, Temples and Grids
1. We first came down as beings of Light and worked with Light to create.  Earth planet was mostly water then, so we came down into the oceans, the easiest medium for us to begin the experiment of taking on dense form.  In the beginning our bodies were very fluid- made of liuid light.  We built crystal cities with our minds and wove them from the fabric of light, which is the essence that we carry within us.  We lived there in harmony, Love, and balance for eons of time.  We breathed the cities into form together, and they sang.  They sang the heart song that we carry within.  each one of us had our own note, our heart song; the crystal amplified that sound and wove it into form.


=== The Great Temple
1. Now let’s add to the former info about eh Great Temple and the work done there.  The crystsal cities had seven levels.  At the highest level and frequency was the Great Temple, the most sacred place in the city, sitting under a domed, clear crystal roof from which a tall crystal spire pointed up directly to the heavens.  There was a large entrance ot the temple with crystal pillars and many steps.  Huge doors twenty feet tall opened outward.  Inside were marble floors, a domed ceiling, and much light coming through.  The Great Temple’s exterior shape was adapted by thought to whatever shape was needed for a particular purpose.
2. Different groups would come in and create whatever their segment needed.  The temple could also change shape internally while remaining the same outside- always with our conscious co-operation with the building.  The temple was full of an kind of light we desired, like many candles for a muted effect or sunlight for a bright, warm light, or light cells/panels- all part of our advanced technology.
3. At certain times when the tall crystal spire of the Great Temple was aligned with the Great Central Sun and the many star systems, the temple teams consisting of gridmasters would receive the energies and transmit them into the city energy grids to be accessed by other elements of our society.  The Energy left the Source of Pure Light.  As it came down closer to denser levels, its codes and glyphs became more visible.  They were in a language of Light, eons old going back as far as history can go.  The gridmasters received the info as shapes/geometry, pictures/visions/glyphs, and/or sounds.  Each gridmaster would receive an aspect, and the team would reassemble all the parts in the center of the circle.  This was an ongoing process, so every aspect of life was receiving new blueprints for continuous improvement.  This is similar to the current process of upgrading computer programs.
4. To do our work, we stood on a star grid on the floor of the Great Temple; the star had as many point as there were members of the team.  Some were teams of twelve who stood on a twelve-pointed star; some were teams of nine standing on a nine-pointed star, etc, depending on the nature of the work and the energy that was coming in. These stars were the focal point of a grid, which then ran down to all the other levels of the city.  We then programmed the new codes into the grids.
5. Each member of the team put the information into the star grid as it was recieved, and the star interconnected with all the other structures in the city.
6. The main grid underlying the entire city was Wholeness and Love.  This was the basic grid, which ensured that every aspect of life and society was in  harmony with the whole.  In addition, each building had its own sacred geometry and received the energy of the whole- The Love Vibration.  Everything and everyone was connected to the whole through the main grid of Wholeness and Love as a unifying matrix.  The gridmasters transmitted the information into the grids, which maintained and supported the city and all the activities in it and sent it to other cities’ temple teams.


=== Aspects of the Outlying Temples’ Circles
1. When the individuals in the other cities gathered in their temple co-creation circles, each circle downloaded information from the grids that was specific to their area of spciality.  each team had its own DNA code for activating a frequency, and each area, such as gardening, technology, healing, architecture, etc.  These teams were adept at downloading and extracting codes for new ways of working in their areas of specialty.  The teams received the new codes and passed them on to others in their area to create whatever was sent.  For instance, they might create a new process to grow plants or a new way to create energy from crystals.  Thus, multiple teams were involved with different aspects with no one team having the entire code.
2. When they extracted codes for their speciality areas, an individual might receive more than one aspect of the incoming blueprint: sound, visual, and/or geometry.
3. For example, someone might receive sound codes and visual codes while someone else might receive geometry and sound codes.  Some downloads were brought in by teams of women only, so it would also be possible for a female to be part of a women-only team.  There were also male-only teams, who worked with downloads that had more male energ involved.  For example, a male-only team might work with architecture while a female-only team would download information on childbirth.
4. It was like a multi-layered matrix with geometries overlapping one another thta could be broken down into different layers; for example, one person receive the sound codes for layer 1, and another person would receive sound aspects for layer 2, while someone else woudl receive the visual aspects for layer 1, etc.
5. More complex blueprints required teams of twelve- usually six feales and six males.  
6. Regardless of the aspects of the teams, all connected through the center of the circle, for it was there that all was jointed together in Oneness to be dispersed throughout the grids.
7. A Great Temple team of gridmasters.
8. Everyone was acting as a separate unit on many levels.
9. New information and activations for the next level of consciousness would arrive when it was time for them to be accessed by others.  In this way the new codes were being transmitted throughout the city, and people were absorbing them directly into their energy fields.  We all hold the blueprint as aprt of ourselves and were born with the matrix of Wholeness. When the time is right, the archive which holds the templates of all creation can be accessed and certain fractions of th eknowledge transmitted.  There were teachers in all the different fields who were initiated to transmit specific parts to others.
10. The new energy added another frequency and dimension of the energy to the grids.  Since the grids were the matrix that supported everything and the disseminators of the energies, their maintenance was essential.  Specific individuals were devoted to this etherically, adjusting, adding, and deleting as it was needed.  Physical work was not needed because everything was so vital and so light-filled that everything co-operated together in divine coordination.


=== The Creation of Light Bodies
1. First, we came in through the tall, crystal spire as our colors.  In the beginning, we were in Light bodies, not physical bodies.  The form for downloading more Lght body images was waiting to be created was in the antenna.  In order for more light bodies to be created, a spiraling energy would come down the antenna under the dome of the Great Temple.  The energy was in a beautiful swirl of colors that twirled, radiating incredible colors.  Our bodies wer elike spheres of Light: blue, pink, violet, lavender, magenta or gold.  Under the dome, the antenna activated the Light body.    Our LIght bodies were fed from Source through the antenna. The temple teams were all swirling spheres of light, just being.  We connected with each other in our consciousness and could interweave with each other, sharing our colors.
2. We were so much part of the whole that everyone’s awareness encompassed everyone else’s and we were never alone.  
3. The Great Temple was on the highest frequency level in the crystal cities… 
4. So did we when we had taken dolphin form.
5. Our bodies where liquid light so we could take any form we liked.
6. Over time, gradually the city took on more shape..  The energy that came otu of the colors and spheres generated a more defined body with hands and features.
7. Dolphin energies helped.  Streams of light came down the spire full of glyphs which held the blueprints.  We could select the blueprint we wanted and then focus our intention into it. Our shape became more triangular with a more defined head and body.  We selected the blueprint and brought it into form by holding it in the colors that we were.  We used our colors to create form. All members of the team contributed their own color and together created a form.


=== From Mer beings to Dolphins
1. The next phase we were denser in form and went form our light bodies in the crystal cities into the oceans as Mer beings.
2. The structures where not solid…. The Mer beings were more like a sperm and an egg with entwined male and female energies, creating fluid structures that were imprinted into the form by intention.  They were created by the male and female spiraling together- the orange/gold/male energy adn the pinkish/purple female energy.  
3. They could shapeshift back and forth between dolphins and Mer Beings.  
4. After that time the Mer Beings became dolphins looking for the shore.  
5. First was a Crystal City made of Light, then the under water city, and then the land came up from under the ocean.
6. The dolphins emerged from the water and created a human body.  Our bodies were liquid light, so assuming any shape we wanted was easy.  
7. First it had hands and feet, but a dolphin head because it was the dolphin’s third eye thta was creating all this from the dolphin galactic brain.
8. We created the first cities on land through intention focused through the third eye.  


=== Assuming Physical Form
1. DNA strands continuously released light codes for each next stage of evolution.  
2. Human stage included more physical structure.
3. Touch changed things instead of just being and creating through thought and visualization.
4. First we were only in the crystal cities on the ocean bottom because there wasn’t much land.  
- “Then we put the energy of the grids into the ley lines which network the whole earth.”
1. Points across the whole earth became receivers and transmitters so that the Grids of Wholeness enveloped the Earth and kept everything in balance and harmony.
2. When the land came up from the water, we decided to take on dense bodies in order to walk on land.  We used the crystal city’s etheric blueprint for the land-based physical city.  Then we used our minds to build cities and temples in those marble and stone cities.


=== The Temple as a Place of Reconnecting to Source
1. The temple was a place to reconnect to Source.
2. Children were brought there to remember who they were.
3. The temple was the highest frequency of the whole city.
4. Everybody had to come regularly so that they could maintain their frequeccy.
5. Everyone was fed by the grid and by their pod (soul group that we cam ein with ) connection.
6. There wan’t so much a feeling of individuality as there is now on the planet Earth.
7. There never was a feeling of alienation and having to do everything alone.  
8. There were so many levels of support.  
9. We had our own pod and the group that we worked within that wa a community.  
10. Then there was a greater community of everybody.


The Role of Water in the Temple
1. A Fountain and water ran under the floor.
2. Worked in Circle Teams
3. When the color of the temple changed, the color of the water changed 
4. And went out into the ocean where it changed the frequency of the planet.
5. If the temple was the heart, then the water that flowed was the arteries that picked up the energy of what we were doing so it could go out and feed the waters of the planet.
6. The water would carry the necessary frequency to restore harmony and balance.  
7. That would change everything, even if what we needed to influence involved the land, for the water would evaporate into the sky and rain on that land.


8. The water also carried the frequency of the geometric shapes which could be invoked by whatever work we were doing.  The combination of the water and the alchemical properties within its consciousness brought the frequency of the geometric shape with it.  Then it would rain, and the wtaer would get to wherever the work needed to be done.
9. Everything was so colorful and so beautiful.  There was water everywhere; waterways were in geometric patterns like spiral flower center of a chrysanthemum
10. The water carried life force through the city to feed everyone.  It carried the frequency of everyone’s love for everyone else; it was a symbiosis of earth, water, people, and plants.  
11. All life forms fed and gave to each other.  The plants would beput into a form that would enable them to transform into something else.  There were no dumps fo rtrash- n place where we threw things away.  When we had finished with something, it transmuted into a new form.
12. The challenge for us now is to bring that memory into our physical bodies and to use more of our brain/thirdeye capacity.
13. Since we moved into the lower chakras after The Fall, we only use a small percentage of our brain, and the rest has atrophied.  We still have it as a potential, but now we have become so gross that we put it into the physical instead of being able to use the capacity that we have.  This Aquarian Time is for us to be more creative in the mental right brain realm.  As we reconnect our DNA strands, we sill have the creative part of the brain again.


Manifesting Our World
1. Info about the Great Temple - the crystals in Lemuria were gargantuan, the size of houses and perfectly clear and smooth as if they had been cut with a diamond saw.
2. All people in perfect trust with the Great Temple as the source of all energy int he city.  
3. Center of temple had a massive crystal which was the place of transmutation.
4. The crystal was a doorway to the universe- its vastness and its power.   This was where matter and energy met and co-mingled.
5. The Great Temple acted as an amplifier that radiated energy everywhere.  The light was all around them, so the whole city and countryside was steeped in this bliss energy.  It was like living in  heaven and they shared that energy with the planet.  Everybody was like a priest or priestess- so elevated and clear with that high frequency energy.
6. Beings were absolutely connected so completely to God consciousness, to the Oneness of everything.


Constructing Buildings
1. Lemurians who were able to go into the archives and download the matrix for the structure coordinated the creation of a building.  They were initiated to bring in the matrix because they were tested on their ability to receive without distortion so they were able to get a perfect blueprint for the building.  They would then transmit parts of the blueprint to the people who were going to make it.
2. Thee frequency, the shape, the color of a building had to be in alignment with the concept of Wholeness of that building since the building had a consciousness.  Otherwise, the building would be a combination of individual efforts.  Even though people had different functions within it, the concept of Wholeness was the unifying principle.
3. Building was done when the energies were very clear.  It was a co-creative process with the consciousness of the liquid light and the team, organically growing a building.  We directed and built it with our minds molding the crystalline structure and holding the consciousness while we worked in rotation because there needed to be someone at the site the entire time.
4. Special seed crystals were grown whose urpose was to expand and grow at an accelerated rate.  We would hold the thought of what we wanted to create in our minds, construct it on the etheric plane, and then attune ourselves to the crystals.  our thoughts would come into symbiotic connection with the crystal, be downloaded into it, and the crystal would manifest our thoughts in the form of a building.  These were very specialized crystals created for this purpose.
5. The crystal was different than the kind of crystal on earth today.
6. It could change form.
7. It could communicate back to the team as it wa growing… it was like a mandala.
8. Water was part of the construction as the binding agent that brought everything together. 
9. Crystal could fed back ideas that would fine-tuen the plan, thus creating a better building as the crystal and water contributed their intelligences ot the team during their creative process. 
10. Crystal and the water grew together so the building would grow fast.
11. The walls formed from teh combination of crystal and water. 
12. We stood in our teple teams in a circle, toning different tones based on our agreed intent before we started and the communication of the building itself.  
13. It created an extraordinarily powerful wave of frequency that went right around the planet.
14. It was amazing what a small number of people could create with a combination of all our energy in symbiosis with the water, crystals, light, everything,  It all worked together.
15. The city was laid out in a circular pattern like a mandala.
16. Circular streets.
17. Rings of streets with buildings between them.  
18. Ever widening circles did the construction go.


Technology


The Fall


1. Lemuria had two distinct time periods, before and after The fall.
2. In the beginning we were constantly connected to the Source by the grids that ran through every part of our cities.
3. In time, we forgot the connection, and that time is known as The Fall.
4. Deeper and deeper levels of disconnection, we moved further away from Source.
5. We didn’t understand as things began to change, and we forgot who we were.  We moved away from remembering that we ere Love and could create our own resources from within.


Being of Service and Sharing Light and Knowledge
1. How did this happen?  There was an evolutionary pull from another plane.
2. Temptation disguised as service . . .
3. We had certain stations in our city where we stood in a circle in our pods and activated beams of light by our intention and sound to teleport ourselves to materialize in the new place.
4. We knew that other civilizations needed the light and help; we had so mcuh knowledge that we wanted to share it with them.  Our lifestyle was so harmonious that we wanted other civilizations to achieve the same level of balance and harmony.
5. In the beginning it was fine; we were able to keep the grids energized because we still had the connection to Source and the other star systems.  
6. The cities and gardens were so beautiful; there were pools and flowers and trees, unicorns and olphisn to play with.  We sill lived in Wholeness, wonder, and joy.  We had fruit and vegetables and trees, and we loved our world.  It was physical paradise without pain.  We wer ethe inncents in the Garden of Eden.


Forgetting Who We Were
1. Lost connection with our star system.
2. more cultural exchanges with the Atlanteans at first.  
3. Atlantis began to degenerate into materialism with its concepts of separation between US and tThem and division between elites and inferiors.  
4. An example of this was the Atlanteans used the cave people to interbreed with animals to make a lower class of slave people to work for them.
5. Materialism gained a foothold in Lemuria and spread like a wild fire.
6. The Atlanteans created the situation that people who were in touch with the star people were “us’ and everyone else was “Them”
7. The star people refused to participate in that, so they withdrew from consciously interacting any longer.
8. We hadn’t realized how much living in the dense vibrations of other civilizations would affect us.
9. We began to forget we were Light and became tooinvolved in their dense frequencies.  
10. This opened the door for lower frequency extra-terrestrials to come in and exploit Earth and her inhabitants.
11. Then we were lost.  We had no roots or connection to our homes.  This was the beginning of th eFall.
12. Once it set in, the cancer spread.  We were on our own.
13. The distortion was love of power, which translated into accumulated wealth.  
14. The off-planet nations were unwilling to give us any more assistance because they felt we were using their gifts in an improper way.


1. While all this was happening, more Lemurians left Lemuria to go around the Earth to help the others return home…. but then they too, got stuck.  Soon the grids had no one to sustain or renew them so the cities began to disintegrate.  
2. At One time, the buildings consciousness was intertwined with the people who created them and worked within them, but that was gone.  Without that interaction, they couldn’t maintain their structure so the cities lost heir strength and dissipated.
3. The Continent of Lemuria sank beneath the ocean.  As Lemurians, we went back to the water and Light from which we had come.  
4. Themission was to bring the Light to the lowest plane of density.  The question was wehther we could maintain the integrity and Wholeness of the Light within us when we descended that far into the density.
5. When lemuria sank, we were interacting with primitive people.  Some became emissaries who were still able to maintain contact telepathically with extra-terrestrial civilizations, but gradually their numbers reduced to just a few people.  Some of the Native American tribes had and still have contact with the star people because they didnt adopt technology so they remained in contact with the land and primitive ways.


Returning to Our Essence
1. The Memory of the Fall is imprinted in our cellular memory.  There are two images.  One is that we are going back to Onenes, to Wholeness while the other is “What happened?”  What went wrong.. How did we fail?   In the end, we abandoned our physical existence and returned to the place of pure ssence.  We returned to innocence.  We need to clear the memory of nto succeeding so we can maintain that sate original innocence in the negativity of the third dimension.
- We can connect with each other in our Light bodies as we did in Lemurian temples because we are beings of Light. 
- We are bringing free, clear, unchained, and unbound Light essence nto our physical bodies as they are now.  
- It doesn’t matter what sate others ar ein around us when we can be the Light.  
- We don’t have to make others any different.  
- If they don’t choose to be in the Light, it doesn’t affect where we are because we are in theLight that helps us to be in the world but not of it.
- We can be unattached to outcomes or experiences because we know who we are.
- If they don’t choose to be in the Light, it doesnt affect where we are because we are in the Light that helps us to be in the world but not of it.


2. When the earth shifts, all our levels and existences will be brought together into Wholeness.  We are not there yet, so as a race we need to reconnect with our teams to help each other to hold the frequency of Love.  
3. Before the Fall, before “us” and “Them” consciousness came from Atlantis, there was a harmony and a holistic quality in everything that existed.  We looked at how each creation was going to affect every aspect of our being.  everything was designed with that paradigm in mind.  If it wasn’t something that was going to benefit every aspect of our beingness, then it wasn’t created.  This element was lost when things started to change into Us and THem, it was left out of the equation.
4. Things got out of balance.  Earth felt it,, shifted and everything came apart.  It was a cleansing similar to what we are  having now


The Return

Those of us who were in Lemuria are the oldeset souls on the planet, the original seedlings.  We have come back fo rthe return to Oneness for ourselves and Earth.  We carry within our DNA the templates for the Lemurian light codes that will activate the earth grids and create the bluepritn of Wholeness for Earth and all its inhabitants.  The blueprint comes down as a matrix.  There are others who have the codes but not those from Lemuria, and they have thei rroles, too.  When these Light does are activated, we will be able to shift our frequencies into the fifth dimensional lightbody and lift ourselves and Earth into Oneness again.


1. eat high vibrational foods and monitor our thoughts.
2. As earth’s vibration increases, ancient temples and crystal cities are being reactivated.
3.  The time for reawakening is now.  The Lemurian temple teams are finding each other.  Each member of the team holds a key aspect that will activate when all the pieces come together.
4. Leumurian gridmasters are receiving the codes and translating them so that they can be received on the Earth Plane.  
5. waves of sound and light are carring the newLight codes.  Those areas that have crystals are amplifiers of energy in theglobal grids.  
6. The vibration for the New Earth is already here.  
7. This is the completion of all our incarnations on the aerth plane.  
8. Here to ground the energies of the Lords of Light, the ELohim, into physicality.  
9. We must remember that we hold the blueprint.
10. As we open it up for ourselves, we open it for all.  
11. Seeking out the others who hold specific resonating DNA so thta we can co-create on a conscious level with those families and groups.  
12. Gathering in our Temple Circles again…. but many of us are not yet aware that is what is occurring.  
13. We only know we are being drawn to one another in spiritual groups wher ewe are remembering our spirits an starting to remember who we are.  
14. This is a revival of the ancient circles in the temples.
15. 







