=== How Enlightenment Changes Your Brain
=== How Enlightenment Changes Your Brain - The New Science of Transformation
=== By Andrew Newberg, MD and Mark Robert Waldman



1. Activity in the frontal or parietal lobes rapidly decreases.  
2. When frontal lobe activity decreaes, however, normal states of conscoiuness and communication are distrupted.
3. “Members of a Pentecostal church will begin to sing and sway as they listen to a sermon or Gospel music.  then they invite the Holy Spirit to enter their consciousness.  Our research showed that when this occurs, practitioners enter a trance state- usually in just a couple of minutes and many begin to speak in a manner that sounds like a strange foreign language.
4. They feel that experience enhances their spiritula conection to the divine, and many Pentecostal churches equate this experience as a direct form of Enlightenment bestoed by the Holy SPirit.  
5. In fact, the Pentecostal movement of the early 1900s gave birth to the notion of evangelical enlightenment,” where direct encounters with God would help to transform the consciousness of humanity, bringing universal liberty, equality, and prosperity to everyone.  
6. When our Pentecostal participants began to speak in tongues, their frontal lobe actiity immediately declined.  The language areas in the frontal lobe also decreased.  
7. SPECT - using single photon emission computed tomography to measure different regions of the brain.  
8. Psychography
9. brief meditation, then a prayer, and then they sat quietly, pen in hand, waiting for the spirits to tell them what to write.  After a few minutes, they began to write furiously.  
10. decrease frontal lobe, decrease temporal lobe, communication centers taken offline.
11. Tap into a unique state where language appear sto flow from a different source.
12. It takes time and practice to dramatically ahcnage neural functioning in a way to deliberately rigger and experience resembling Enlightenment.  
