

=== ISIS IN AMERICA

=== By Henry Steel Olcott

=== quick_notes

1. “A big writin-table”
2. “As if for dear life until bodily fatigue we would compel us to stop.”
3. Amanuensis - one employed to write from dictation or to copy manuscript; proof reader - collaborator
4. “idea came creaming through her mind like a perennial spring which is ever over flowing it’s brim.”
5. Writing upon Brahma
6. Quoting Porphyrius
7. Critical cudgel
8. rivulet
9. “Shad had no plan”
10. “She was but the channel through which dthe tide of fresh, vital essence was being poured…”
11. “The stagnant pool of modern spiritual thought.”
12. Cut and pasted 
13. Recut and re-pasted
14. Six, or eight or ten slips cut cut from other pages- pasted together.
15. Text joined by interlined words or sentences.
16. BHV - first appearance in Daily Graphic in 1874.
17. she “got the person to write down his vies or reminiscences for insertion in her book.
18. Jewish Rabbi spoke to her on Kabballa  and she had taught him things he had not even dreamed of.
19. “Thrown a clear light on passages which not even his best teachers understood.
20. She dazzled and astonished most erudite: (having or showing knowledge that is gained by studying : possessing or displaying erudition) by her learning quite as much as she dazzled all present by her eloquence and delighted them by her wit an dhumorous raillery.
21. Numerous quotations in Isis Unveiled - only from 100 books of reference.
22. Example Books:  
    A. King’s gnostics
    B. Jenning’s Rosicrucians
    C. Dunlop’s Sod and Spirit - History of Man
    D. Moor’s Hindu Pantheon
    E. Des Mousseaux’s furious attacks on Magic, Mesmerism, and spiritualism.
    Jacollit’s twenty-seven volumes
    max Mueller, Huxley, Tyndalls, herbert Spencer
23. Many others of greater or lesser “repute”
24. he had Prepared the various copious index of some fifty pages.
25.  and did the auxillary work
26. books came from the “ASTRAL LIGHT”; from her “Soul Senses”, from her teachers, the “Brothers, “Adepts”, “Sages” “Masters”, as they have been variously called.
27. He sat at the opposite side of one big table.
28. Her pen would by flying over the pages.
29. “I went, and found the two volumes wanted which, to my knowledge, had not beein the house until that very moment.”
30. etagere: a piece of furniture consisting of a set of open shelves for displaying small objects and sometimes having an enclosed cabinet as a base - apport: meaning obsolete.
31. “I looked again, in that direction and the books had disappeared.”
32. Never more then 2 of the styles on the same page. (caligraphic)… sometimes 3 or 4.
33. Most perfect were manuscript written while she was sleeping.
34. The civilization of Ancient Egypt
35. Smoke and chat when they where done.
36. One night he went to sleep and she had written 30 or 40 pages by a maste.r
37. “caves and Jugles of Hinustan
38. She would leave the room one person and return another- tricks of motions, speech and manners changed.
39. Benevolent patience from the masters… but she had tantrums as well.
40. When the body was occupied by a sage it would be forced to act with a sage’s tranquility.
41. She never had to think, “Can I write on this subject?” or “Am I equal to the task?”  I simply sit down and write.
42. Why?  Because somebody who knows all dictates it to me.
43. When ever I write upon a subject I know little or nothign of it.
44. I have never been unconscious one single instant.
45. “I am soley occupied not with writing Isis, but with Isis herself.
46. I live in a kind of permanent enchantement, a life of visions and sights with open eyes, and no chance whatever to decive my senses.
47. Long lost secrets
48. Veil thinner and more transparent - falls off before my eyes.
49. Path magazine - 1894
50. Body occupied at such times
51. LIterary work done by foreign entities who taught me through her lips and gave out knowledge of hiwch she herself did not possess even a glimering in her normal state.
52. Isis Unveiled:  Volume I: questions of Science; Volume Ii - Religion; but portions belong in the other section at times.
53. Peremptorily
54. A 3rd Volume was destroyed.
55. Mahatmas - pin faith too.
56. Next chapter is Different Hypothesis.
57. 

