
=== Kung Fu 

=== History, Philosophy and Technique

=== By David Chow and Richard Spangler




The Father of Shaolin Ch’uan 7:

1. The unarmed defense principles were advanced through CH’an Buddhist religious practices during the sixth century.
2. The holy man considered by most modern sources to be the father of the martial arts is Bodhidharma.
3. Bodhidharma is the 28th Indian patriarch exalted by orthodox CH’an tradition.  
4. Bodhidharma - called P u titamo by the Chinese lived circa A.D. 448-527.
5. Bodhidharma believed to be the father of Shaolin Temple boxing.  
6. He crossed the Yangtze River
7. He walked hundreds of miles to reach Northern China…crossed the freezing Himalayan Mountains.
8. He first went to Nanking, he was summoned before the court of Liang Wu Ti  A.D. 502-49…. monarch of one of the kingdoms established during the Six Dynasties periods.

Emperor Wu said, “We have constructed many temples, copied the holy scriptures, and supported many monks and nuns.  What merit is there in our conduct, Revered Sir?”

“No merit at all,” re replied.  Those are inferior deeds containing vestiges of worldiness which are akin to shadows in the forst.  They only appear to exist. In reality they have no substance.  The only true work of merit is Widsom, pure, perfect and mysterioius, which is not to be won through material acts.

Appalled a tthe response, which to him indicated thta his presumed great efforts were being condemned, the Chinese ruler inquired agian, “What, then, is the holy truth in its highest sense?”

In vast emptiness there is nothing holy,” said Bodhidharma.  Finally, in exasperation, the Emperor asked, “Who is it, then, confronting me now?”

“I know not, your majesty,” was his baffeling answer.  Dumfounded, Emperor Wu dismissed Bodhidharma and stalked off in an uncomprehending rage as the mystical wise man with the great black beard walked serenely out of the royal palace never to reutrn.

The Emperor, feelign that he could buy his way into Buddhahood, simply was not aware of the true essence of Ch’an, which is the perception of self-nature.  He did not realize that what he had asked was not verbally answerable fromt he CH’an viewpoint. -
“The nature of the mind when understood, no human speech can compass or disclose.  Enlightenment is naught to be attained, and he that gains it does not say what he knows.  Salvation could only be achieved by inward enlightenment, i.e., illumination could not be outwardly communicated.  material offerings were considered secondary, if not totally in vain. IF he had understood this, he would have reached at least one level of realization.  As Ch’an monks say, “Understanding- this one word is the source of all mysteries.”

As an ancient legend contends, “Riding on the blade of a reed (a leaf-shaped ferryboat), Bodhidharma crossed the Yangtze River and went to north to Loyang,” the capital of Honan Province, where, in the neighboring densely foreset, mountainous countryside, he found the Shaolin Ssu (Young FOrest Temple) along the northern side of Shao-Shih Mountain south of SUng San Mountain.

The monastery, built by Emperior Hsiao When of Northern Wei Dynasty (a.d. 386-534) had become famous as the site for scholarly translations of immense works of Buddhist scripture into Chinese.    Monks purportedly toiled as scribes in shifts, day and night, translating over six hundred sacred Sanskirt books into their native language.

Upon Bodhidharma’s arrival, however, the fang Chang (“head Monk”) feared that the sage’s reformist CH’anism, which dismissed book learning as irrelevant, might disrupt the monastery’s more traditional tenets of Buddhism.  Fang Chang directed him to remain outside of the temple.  thus, this last Indian patriarch, who was to become China’s first Ch’an patriarch, took refuge in a nearby cave.  

Bodhidharma “originally came to Chian to transmit the teaching and save deluded beings.”  His task was seemingly impossible.  

Dana R. Fraser, in the Recorded Sayings of Layman P’ang, said that “though teachers of various types of Buddhist meditation had preceded him, none had been able to establish a school or line of disciples.  Nevertheless, he was determined to show that Supreme Wisdom had nothing to do with orthodox performances, ritualistic practices, or rendering Sanskrit to Chinese.

Western culture finds his solution difficult to fathom, if not completely incredible.  This monumental mystic began to sit in cross-legged meditaiton facing a rock cliff next to Shaolin Monastery.  He remained there in absolute silence for nine yaers.  This Ch’an sitting” was thought to aid those who encountered insurmountable obstructions. But do not get the impression that Bodhidharma was staring at the rock wall for twenty-four hours a day.  This, despite some fanciful Ch’an histories, is not true.

one account suggets that he meditated on a mat of leaves for two-hour periods at dawn and dusk with further contemplation inside his cave.  


                Unable to to discern the meaning behind his philosophy of silence.


Bodhidharma was saying, “Put an end to the formation of all external relationships and be rid of any vehment desires inside your heart; then with a mind like a wall, indifferent to outside disruption, you may enter into the truth.”

In less inspired Ch’an biographies, it is related thta at the end of the nine years Bodhidharma’s large, deep blue piercing eyes did exactly that; his powerfully steady gaze had drilled a gaping hole in the cliff wall.  After seing the eye-riveted orifice, the stunned Shaolin Fang CHang could no longer resist his obviously superior authority.  Bodhidharma entered the Shaolin Monastery gates to become the first Tsu (patriarch or, literally, ancestor) of the Ch’an sect in CHina.

“The comparable doctrine of True Buddhism can be understood only after long, hard discipline and by enduring what is most difficult to endure, and by practicing what is most difficult to practice.  Men of inferior virtue and wisdom will not coprehend it. All their labors will come to nothing, he told his first disciple, Hui-k’o.

Bodhidharma explained to the monks that body and soul are inseparable.  This unity must be invigorated for enlightenment.  The legend continues that physical fitness became a part of Shaolin life with his introduction of systematized exercises to strengthen the body and mind.  Self-defense movements were devised later from Bodhidharma’s knowledge of Indian fighting systems.   Forms:  1. The Muscle Change Classic or The Change of Winews, 2. The Marrow washing and 3. The Eighteen Hand movements of the Enlighted One (The Eightteen Lo Han SHou).




Taoist Contribution to Kung Fu 14:
“bamboo parchment”
The greatest of all Chinese philosophers to arise out of the centuries of revolutionary instability and excessive treachery was the imposing figure of Confucious (Kung Futzu c 551-479BC.   - what came to be known as “Hundred Schools of Thought” The chinese hundred may be defined as “many” in western terms.  

The most influential, after the Confucians, were the Taoists, who directed their teachings toward the individual search for a higher form of physical and mental existance.  Since Taoism (pronounced Dowism), despite its matter-of-fact practical aspects, has been called the most enigmatic of all Chinese philosophies.”  But be good to compare it with better understood Confucianism.

Beauson Tseng, a contemporary Chinese philosopher, summed up the main difference in terms:


”If the Ways of Heaven of Nature (the Tao) be likened to an ocean, the fellow who exerts himself and makes wise use of his knowledge of hydrodynamics to swim in a beeline to his chose destination- is a Confucianist. The other fellow, who holds that the most ideal spot for him is where the winds and currents will of themselves carry him to- Is a Taoist.  The more man lets science have free play, the more science can be made to serve man.  Tao behaves much in the same way as science.” 


 While most of the other philosophical schools, including the Confucians and Legalists, were promulgated for sociopolitical problem-solving through regulations and laws, the anarchistic taoists advocated the “The more restrictions and prohibitions there are in the law books, the more thieves and bandits there will be.”
 
 Troubled Taoist thinkers felt it best to transcend earthly suffering by withdrawing from the ill-conceived man-made “civilizaiton” and join or rejoin the natural forces of life.  They were convinced that this could be accomplished by living absolutely detached from organized society as contemplative hermits deeply secluded in the wilderness of the mountains and forests.
 
 unlike Buddhist tenets, Taoism does not promise emancipating nirvana or entry to the Pure Land of Bliss at the end of spiritual pursuit.  Neither does it offer salvation that delivers men from misery after death.  On the contrary, the Taoists treasure life because to them living is supremely sweet and enjoyable after being secured by nature’s rhythms.
 
 Tao Te Ching - classic liteary work - pronounced Dow Duh Jing, its meaning is inexpressible in words, “The Tao that can be named is not everlasting Tao”
 
 The eight-one “flowers” beautiful chapters of the Tao Te Ching (meaning “The way and Its Power”) are attributed to Lao Tau , the traditional father of Taoism in the fourth century B.C.The mysterious sage was a native of Lu I County in Honan Proince.  He lived approximately a hundred years 580-480bc).  Since he had the apperance of an old man in his youth, Lao Tzu Old Master became his sobriquet.  His true name was Li Erh.
 
 He served ably in the Chou court as the guardian of the imperial library.  He left his native land and pursue virtue in a more congenial atmopshere…
 
 The gatekeeper, Yin Hsi recognized him as a renounded philosopher and asked him “Oh, Master, before you retreat from the world would you kindly write down your way of living for me?  lao Tzu consented and wrote his “Tao Te Ching, his entire philosophy compressed into some five thousand pithy idographs.    The great mystic then left the Middle Kingdom (China) and traveled to the west on a water buffalo.  He was never seen agian…
 
 Aphoristic Tao E Ching has exerted a tremendous influence not only in China but the rest of the world.  Over forty version of it in English with at least seven hundred commentaries in CHinese.
 
 Certain Taoist ideas were considered long before the apperance of Lao Tzu.  If we examine the I Ching (Ee Jing) known as the book of changes in English, we will discover many Taoist concepts.   May date back to the 6th century before Christ….
 
 we see the first mention of the Tao and Yinn and Yang, dealing with the duality of nature: Yin and Yang, together they are called Tao.
 
 They existed before the universe was born.
 
 Tao has no limites.
 Its existence is ternal.
 tao is not a supernatural force.
 It is the ultimate principle of the universe.
 Tao is the prime element from which everything is created in nature.
 
 Tao has two forces Yin and Yang.  Yin is characterized s the negative force of darkness, coldness and emptiness.  Yang stands for the positive energy which produces light, warmth and fullness.  
 
 These alternating forces are indestructible and inexhaustible.  They contradict as well as complement each other.  This “eternal duality” may be explained further as the primordial paired potencies that regular the universe….
 
 Te the power.. the manifestation of tao.  this means that every boject or subtance possess positive and negative elements within itself.  . . .
 
 The Taoist sage, on the other hand, would say, “To be and not to be.  That is the answer!”  
 
 This is the Taoist law of nature.  To really be vitally alive, to truly feel life’s offerings, is to know the ighs and lows, the exhilaration of the mountiantop and the descent to the valley, and to accept and enjoy not one but both.  Life’s highs are most invigorating; there is also fertileness to be found in the lowest valley.  
 
 The famous Chinese Ying-Yang symbol surrounded by eight trigrams which figuratively express nature and its changes.
 
 
 “The Tao never acts, yet nothign is left undone.” - Tao Te Ching, Chapte r81.
 
 The passive principle of Wu Wei cnnotes spontaneous responsiveness to nature.  Deliberate eforts to alter nature can only lead man into confusion and entanglement.  This typical Taoist concept of spontaneity undoubtedly inspired much of the philosophy behind the physical traning of Kung Fu.  Kung Fu was not an art developed to perpetrate violence.  It was designed to be responsive to otuside or hostile forces only when necessary.
 
 Lao Tzu postulated the idea of Wu Wei, tranlasted into “nonaction” to explain man’s appropriate relationship with nature.  Nonactino does not mean idleness, apathy or indifference to the Taoist; it rather implies the unresisting attitude that he adopts as he abides and communes with nature.  
 
 To be suitablly “not active” man must also discard ambitious desires, for desire is the initiating force which engages man’s active movement.  
 
 The greatest revelation of Tao lies in “stillness”  , that “stillness” must be preserved in the inner being by dismissing all motivtes that would disturb it or draw it into action.  Do not move in response to outward inducements but only to that which is within and spontaneous.  When man eventually transcends his self-ego and merges himself with nature, he is then in union with the Tao.  Thus, Lao Tzu emphasied that man should be aware of the active principel but should stay with the passive principle.
 
 Taoist disposition of patiently receiving or enduring without reistance.  He knows that eventually the sun will shine brightly from behidn the darkest of clouds.   This is the ssence of “achievement without doing.”
 
 This typical Taoist concept of spontaneity undoubtedly inspired much of the philosophy behidn the physical training of Kung Fu.  ….
 
 any motion may be formed to be “Wu Wei” by dedicated practice…. 
 The Wu Wei punch….
 
 “Those who actively initiate will be defeated;
 Those who hold fast to anything will lose it.
 Therefore, the Sage is never defeated because he is passive,
 and never loses because he is detached - Tao Te CHing.
 
 Taoist priest Chang San-feng, the legendary creator of T’ai Chi Chu’uan, “The Grand Ultimate Fist.”
 
 Tai Chi, written about first in the Ancient I-Ching represents the primary cause of the existence of the universe.
 
 tao is said to be the universal principle that constitutes the material world, it possess a motion of the positive and negative forces revolving within itself.
 
 It can not generate itself it is generated by T’ai Chi.  T’ai Chi, as the reality of the universe, is the abode of Tao, the ultimate law of the universe.  There is no supernatural power attached to the “Grand Ultimate” nor is there any force in T’ai Chi itself.  It signifies a “dynamic tranquillity” residing in a state of nothingess.”
 
 No force exists within the tranquil state of the “grand Ultimate”  Thus, T’ai Chi is said to posses a soft quality.  . . . from this quality yin and yang are generated within the context of Tao.
 
 

                 “My own destiny depends upon myself and not upon heaven.”

This meant that Taoism represented an individulaist philosophy of salvation; therefore, Chang’s primary pursuit was to find out how to preseve his life and avoid harm and death.  He began a serach for methods of immortalizaiton…he spent ten yars at the SHaolin Monastery mastering CH’an BUddhist meditaiton and self-defense arts.  Despite becoming a revered Shaolin CH’uan master, CHang felt that his personal goal remained unfulfilled.  He decided to retreat to the verdant Wu Tang mountain range in Hupeh Province.  The Wu Tang Mountains had always been a favorite hermitage of the recluvisve Taoists.  As the legend tells us, Chang was contemplating inside his but when, around high noon one day, he heard some strange noises outside.  Change saw a snake….


            a perfect example of a yielding force overpowering a superior strength.
        but the reptile repeatedly evaded the onsalught by circular twisting and winding away from the direct thrusts of the hawk’s sharply hooked bill.  The hawk tried to poke again and again…. the bird became fatigued from its continous but fruitless attacks.

From this inspriation the classic Tai Chi Chuan system of exercises was formed, Calling upon the Yin-Yang principle where opposites interact with each other as a means to an end.  





Philosophical Vignettes 216:
Ch’en conintues his taoist thesis of life-preserving possiblities by saying that the “original vital essence” must remain intact or be saved from decay by keeping the body as “supple as a babe’s”  The difficulty, according to CH’en, “lies in protecting the “original vital essence” from evaporation”  The farther man gets away from his primal state, the closer he is to the extinction of death.

The practice of “Chinese shadow boxing” yet another term ofor Tai Chi CHuan, can be of benefit to anyone at any time during the day….

An exercise stand of Nei Kung designed to absorb the power of the air. Eighty-five-year-old Keu Ling YIng, originally from interior CHina, resides in San Francisco, where he is known as America’s greatest master of Nei Kung.  As he expresses his martial arts philosophy:

“ Big moves are not as polished as short moves.  Short moves are not as polished as stillness.”

Pa Kau Ch’uan practitioner needs - circular avoidance movements followd by palm strikes.  All basic, to the point, but quick and effective.  

The unusual aspect of this “martial art” is that it does not contain specific “fighting” techniques as most other styles do.   There no methods of kicking or fist stirking.  instead, Pa Kau CH’uan is a marvelouss system of defense created to avoid intended aggresison through the elusive beauty of unseen movement.  

Baffling circular gyrations causing him to vanish before the opponent’s eyes.  Whereas he actually has circled behidn his attacker for  afraction of as econd, sufficient time to incapacitate him with an open or closed palm blow.

Featuring focused internal strength, the palm strike wiill provide more than enough power to discourage the antagonist.  circular avoidance mvoements followed by palm strikes.  Low foot strikes can be used.  

Attempts to penetrate the circle of a Pa Kua CH’uan master would be folly for a street fighter, especially one used to head-on linear punching and kicking.  Thus, this “Eight Diagram Fist” discipline, covering the circular spectrum…. has something to offer the student who wishes to master defensive body motion… supported by the least amount of violent agression.

The creator of Hsing I cannot be authenticated with an yhistorical accuracy….  that General yeh Fei originated the system in the Sung dynasty…. 

Hsing I is learnd with pa Kuan Ch’uan.. themost martial of the three leading internal systems.  




                    The Thorny Rose
                    Why should a peaceful nation have military forces and arms?
                    Why should a polite police officer carry a pistol?
                    Why should a friendly neighbor study the martial arts?
                    And even more…
                    Why should a priest learn Kung Fu?
                    The Thorn Defends the Rose and harms only those who would steal the Blossom.





Iron Forearm Kung:
Iron FOrearm Kung, also known as the Iron Pole, is thought to be one of the ismpler and eaaier-to-master Kung Fu Techniques..

Lightly striking the inner and outer forearms against the firm, upright wooden support, for example… 

fifteen minutes a session, twice a day.

Six monthes later begin hitting the column harder.

You will notice that the forearms can accept and tolerate the steady striking.
They gradually become strengthened and hardened.  
Continue this for six more months.
Then train against heavy tree trunk covered with coarse bark. 
This will enable the skin, muscle and bone to develop more resistance against a rough and hard surface.  
An hour a day for 2 years.
Repeat with large rocks….
smooth rocks first, and later uneven rones….
Finally, concentrate on the rough rocks until a disciple can swing his arms freely and from any direciton instanly shattering one with either arm.

The arms, now with the strength and hardness of lead pipes, are potential lethal weapons for the preservatin of peace.  This, then is Iron FOrearm Kung.







