
=== Mystics & Miracles

=== True Stories of Lives Touched by God

=== By Bert Ghezzi



Front Flap:
“Mystics are people who have been introduced into the mysteries of Christ’s death and resurrection.  In a sense, all Christians are mystics.  But not all Christians enjoy a special closeness to God- this is what sets the mystics apart.  In these compelling life sketches, Bert Ghezzi highlights the miracles and the extraordinary lives of the mystics while reminding us of their humanity.  He brings them within reach and onto level ground, where we can learn from them and find inspiration in their lives of faith in God.  

I tell you the truth, anyone who has faith in me will do what I have been doing.  He will do even greater things than these, because I am going to the Father.  And I will do whatever you ask in  my name, so that the Son may bring glory to the Father. - John 14:12-13


Miracles that changed the course of history


Miraculous Voices - St. Joan of Arc (1412-31) pg 149:

“Nearly all the saints had a “religious” task to perform, and they had to leave the owlrd, so as to be free to accomplish it.  But Joan breaks through this rule.

She was called to perform a purely worldly task, to free a people from unendurable political misery, to st a rightful king on the throne, to expel the enemy.  She doesn’t leave the world because of her mission.  because of it she goes into the world, right into most dangerous places, into the court, into camp, into war.” - IDA COUDENHOVE

“The church officially remembers Joan of Arc not as a martyr but as a virgin- the Maid of Orleans.  Of course, Joan was a martyr, but not in the technical sense.  Yes, she died because she did what she thought God wanted her to do.  But she was killed for her politics, not for her faith.  Pagans did not execute her for defeating them.  Political enemies burned her at the stake for defeating them at war.

Paradoxically, Christian people, good and bad alike, cheered at her demise.  Other Christians wept.  This incongruity may trouble us, but Joan would have expected it.  The war she fought embroiled French Christians against English Christians.  We too have waged wars like that, pitting Christian against Christian.  Just as we may have felt that God was on our side, Joan believed that God was with the French.  When the judges who condemned her asked if the heavenly voices she followed to war spoke in English, she replied tartly, “Why should they speak English when they were not on the English side?”

Joan of Arc was born into the violent times of the fifteenth century.  During her childhood, King Henry V of England invaded France and seized Normandy.  He laid claim to the crown of the French king, Charles VI, who was mentally ill.  Paralyzed by civil war between the duke of Burgundy and the duke of Orleans, the French could not put up much of a defense.  Things worsened when agents of the duke of Orleans murdered the duke of Burgundy.  The Burgundians reacted by becoming England’s allies.  

Eventually, Burgundian mercenaries brought the war home to Joan’s family.  The raiders sacked the little village of Domremy-la-Pucelle, forcing them to flee.  Thus, the indiscriminate brutality of war disrupted Joan of Arc’s pleasant childhood to acquaint her with fear.

Both the English king and the French king died in 1422, but their successors pursued the war.  The English, with Burgundian support, marched steadily across France, taking one town at a time.  Charles VII, the heir to the French throne, was not yet crowned or anointed king.  The enemy controlled the road to Reims, the traditional site where French kings were crowned.  Regarding the situation as hopeless, the future kin languished with his court near Orleans.

In 1424, when Joan was only twelve years old, the great miracle of her life unfolded.  One summer day in her father’s garden, she heard a mysterious voice, which was accompanied by a bright light.   “At first I was very much frightened,” she said later.  “The voice came toward the hour of noon.  I had fasted the preceding day.  I heard the voice on my right hand, in the direction of the church.  I seldom hear it without seeing a light.  The light always appears on the side from which I hear the voice.”

She identified the speaker as Michael the Archangel.  Subsequently, he spoke to her many times, gradually revealing a preposterous mission.  “You have been chosen to restore the kingdom of France,” said the voice, “and to protect King Charles.”  She was to accomplish these things as the head of the army!  Imagine the terror and confusion the archangel’s messages must have caused young Joan.

Michael also told her that St. Catherine and St. Margaret would appear to her.  God was sending these saints, he said, so she must obey their directions.  Over the next seven years, Michael, Catherine, and Margaret are said to have visited Joan frequently, sometimes several times a day.  Not only could she see and hear her heavenly messengers, but she could also touch and smell them.  At her trial she testified that she physically embraced the saints and that they had a pleasant fragrance.

Joan found the visions comforting, but they also put her undergreat stress.  Fear of her strict father compelled her to keep them secret; she confided only in her parish priest.  The messages must have both thrilled and troubled her.  The revelations conflicted with reality.  How would a simple pleasant girl accomplish such imposing, if not impossible, tasks?

By May 1428, Joan’s voices had become relentless and specific.  They directed her to go at once to a town nearby and to offer her services to Robert de Baudricourt, the commander of the royal forces.  Reluctantly, she obeyed.  De Baudricourt, however, greeted her with laughter, telling her that her father should give her a good spanking.

At that time, conditions were deteriorating for the French.  The English had put Orleans under siege, and the stronghold was in grave danger.  Joan’s voices became more insistent. “But I am merely a girl! I cannot ride a horse or wield a weapon!” she protested.  

“It is God who commands it!” came the reply.

Unable to resist any longer, Joan secretly made her way back to Baudricourt.  When she arrived she told the commander a fact she could have known only by revelation.  She said the French army- on that very day- had suffered a defeat near Orleans.  Joan urged him to send her to Orleans so that she might fulfill her mission.  When official reports confirmed Joan’s word, de Baudricourt finally took her seriously and sent her to Charles VII.

Charles kept Joan waiting three days before he admitted her to court.  When Joan entered, the king was in disguise, hiding among his courtiers.  But Joan went directly to him.  The voices had given her a secret sign, and when she communicated it to Charles, it convinced him of her authenticity.  Pressed by suspicious advisers, he had a team of theologians examine Joan at Poitiers.  They discerned no problems and recommended that Charles make judicious use of her services.

Thus the way was cleared for Joan of Arc to fulfill her divinely appointed task.  She was outfitted with white armor and provided a special standard bearing the names Jesus and Mary.
The banner depicted two kneeling angels offering a fleur-de-lis to God.  On April 29, 1429, Joan led her army into Orleans.  Miraculously, she rallied the town.  By May 8, the French had captured the English forts and had lifted the siege.  An arrow had penetrated the armor over Joan’s breast, but the injury was not serious enough to keep her out of the battle.  Everything, including the wound, occurred exactly as Joan had prophesied before the campaign.  A peasant maiden had defeated the army of a mighty kingdom, a humiliation that demanded revenge.

The way to Reims was now open. Joan urged the immediate coronation of the king, but the French leaders dragged their feet.  Finally, however, at Reims on July 17th, 1429, Charles VII was anointed king of France.  The Maid of Orleans stood triumphantly at his side.  Joan had accomplished her mission.

During the battles at Orleans, the voices had told Joan she had only a little time left.  Her shameful end lurked ominously in the shadows.  Later, she sustained a serious arrow wound in the thigh during an unsuccessful attack on Paris.  In May 1430, after spending the winter in court, she led a force to relieve Compiegne which the Burgundians had under siege.  Her effort failed, and the Burgundians captured her.

Through the summer and fall, the duke of Burgundy held Joan captive.  The French, apparently ungrateful, made no effort to rescue her or obtain her release.  On November 21, 1430, the burgundians sold Joan to the English for a large sum.  The English were quite eager to punish the maiden who had bested them.

They could not execute Joan for winning, but they could impose capital punishment for sorcery or heresy.  For several months she was chained in a cell in the castle at Rouen, where five coarse guards constantly taunted her.  In February 1431, Joan appeared before tribunal headed by Peter Cauchon, the avaricious and wicked bishop of Beauvais.

Joan had no chance for a fair trial.  She stood alone before devious judges, an uneducated girl conducting her own defense.  The panel interrogated her six times in public, nine times in private.  They questioned her closely about her visions, voices, male dress, faith, and submissiveness to the church.  Giving good, sometimes even unexpectedly clever answers, Joan handled herself courageously.  However, the judges took advantage of her lack of education and tripped her up on a few slippery theological points.  The panel packed its summary with her damaging replies and condemned her with that unfair report.  They declared that demons inspired her revelations.

The tribunal decided that unless Joan recanted, she was to die as a heretic.  At first she refused.  But later, when she was taken before a huge throng, she seems to have made some sort of retraction.  When she was returned to prison, however, somehow she was tricked into wearing men’s clohting, which she had promised to forsake.

Cauchon visited her, observed her dress, and determined that she had fallen back into error.  Joan, her strength renewed, then repudiated her earlier retraction.  She declared that God had truely commissioned her and that her voices had come from him.  “Be of good cheer!” Cauchon said to an English lord as he left the castle.  “We’ll get her yet!”  Cauchon reported these events to the tribunal.  On his word, on May 29, 1431, having condemned Joan of Arc as a relapsed heretic, the judges remanded her to the state for execution.  The next morning she was taken into Rouen’s public square and burned at the stake.

Like Jesus’ life, Joan of Arc’s life seemed to end in failure.

Twenty-three yaers later, however, Joan’s mother and brothers asked that her case be reopened.  Pope Callistus III appointed a commission to review the matter.  in 1456, the new panel repudiated the trial and verdict and completely restored Joan’s reputation. Once again her piety and exemplary conduct had triumphed.

Few Christians hear heaven-sent voices.  I know I don’t.  Joan was one of those rare exceptions who did.  She obeyed what she perceived to be God’s directions, and against all odds she achieved the purpose she was given. Though I’ve never heard a heaven-sent voice, now and then I sense something God wants of me.  Doesn’t that also happen to you?  Perhaps Joan’s example will reach down through the centuries to encourage us to listen closely for and to obey God’s message to us.

The Death of St. Joan
And when they had come into the market square there was a great concourse of many thousands awaiting them, and in the midst was a heap of mortar very high, hardened to stone, and a tall stake standing in it, and the faggots piled around it.  These, after one deputed had preached at her, she mounted without faltering, and was chained to the stake.  But being there, above the people, and seen by all, she forgave her enemies and begged each priest in that multitude to say one Mass for her soul

Then she asked for a cross, and an English soldier bound two sticks together and held it up for her to take, which she kissed and put into the bosom of her white robe.  She asked also for a crucifix from the church at hand, and this was found and given her.  And when she had held this up before her and kissed it also fervently, while the English lords clamored at the delay, the torch was set to the faggots and in the midst of the smoke they heard her proclaiming firmly that indeed hermission was of God, and they heard her praying to the saints; til, in a very little while, a loud voice came from the midst of the burning, the holy name Jesus, called so loudly that every man heard it to the very ends of the square.  And after that there was silence, and no sound but the crackling of the fire.  - Hilaire Belloc



Miracles Over Magic
St. Patrick (C. 389-C.461

Ireland, which never had the knowledge of God, but up till now always adored idols and things unclean- how are they now made a people of the Lord, and are called children of God?  The sons of the Scots and the daughters of their chieftains are seen to become monks and virgins of Christ - St Patrick.


1. Wear green on St. Patrick’s Day.
2. Shenanigans on feast day.
3. Patrick would enjoy the hoopla
4. Patrick might want to enhance the day with Christian customs, as many do in Ireland.  
5. Like taking time out to pray or to study the Bible or to share a word of faith with a neighbor.
6. Prayer, study, and evangelism were the real hallmarks of his life.

Patrick first came to Ireland as a slave in 405, when raiders tore him and many others from their homes in Roman Britain.  For six years, near a mountain in northern Ireland, Patrick herded swine for his pagan master.  In his Confession, eh says that his bondage was a time of spiritual strengthening.  “My love and fear of God,” he aid, “increased greatly, and my faith grew, and my spirit was stirred up.”

He spend his days and nights praying.  “Before dawn, in snow and frost and rain, I used to be aroused to prayer,” he recalled.  “Nor was there any tepidity in me, such as I now feel, because then the spirit was fervent within me.”

One night, Patrick heard a heavenly voice in his dreams that revealed he would soon return to his homeland.  Later on, the voice spoke of a ship two hundred miles away that would carry him to Britain.  Patrick fled from his master and walked the logn distance to the boat.  When he arrived, the captain at first refused to take him.  After Patrick prayed, however, the captain reconsidered and gave him passage.

The ship reached shore in three days.  Then Patrick and the sailors trekked for a month through rough terrain.  When their food ran out, the shipmaster challenged him to pray to his God for help.  “Turn earnestly,” said Patrick, “and with all your hearts to the Lord my God, to whom nothing is impossible.”  Just then a herd of swine appeared on the road, and the pigs soon became a hearty barbecue.  Until Patrick left the seamen a month later, they did not lack for food or anything else.

Patrick was about twenty-two years old when he rejoined his family.  They welcomed him warmly, hoping he would never again leave them.  But that was not to be.  He soon received dreams that urged him to return to Ireland.  “ heard,” he wrote, “the voices of those who dwelt beside the wood of Focluth, which is by the western sea.  And thus they cried, as if with on emouth: “We beg you, holy youth, to come and walk once more among us.”  Patrick understood that God was calling him to take the gospel to Ireland.  In fact, to become the Apostle of Ireland.

continued…


1. patrick went to France, where he worked for twenty-one years preparing for his mission.
2. Establishing the Christian church in Ireland would require many things.  Provide news to pagan people.
3. He would have to posses the strength and savvy to overcome the resistance of the druids, the priests who used magic to dominate the Irish.
4. For three years, Patrick devoted himself to acquiring spiritual disciplines and practical skills at the Monastery of Lerins.
5. Fifteen more at Auxerre, where the great monk and bishop St Germanus was his mentor.
6. He trained to be a church planter, not a scholar.  He needed pastoral wisdom more than scholarship.
7. He was ordained a deason and a priest.  
8. Ireland’s first bishop, St palladius, died in 431 after only one year of service.  Patrick succeeded him as bishop and launched his divinely appointed enterprise in 432.
9. Spring 433 - determined to win support of High-King Laoghaire, the powerful ruler of central Ireland.
10. His resolve to gain the king’s support precipitated a dramatic confrontation with leading druids.  
11. Patrick’s triumph over them in a contest of spiritual power versus magic secured the success of his mission at its outset.
12. It happened on the night before Easter.  Laoghaire was celebrating a pagan festival at Tara… his base in central Ireland.  No one could kindle a fire until the ceremonial beacon on Royal Hill was lit.  
13. Miles away atop the Hill of Slane, Patrick had gathered his followers for the Easter Vigial… unaware of the prohibition against fires….  Patrick strikes a new fire.
14. Fire is the vivid symbol of Christ’s resurrection.  Had he known of the prohibition he probably would of ignored it anyway.  
15. King Laoghaire saw the fire.  The druids, sensing imminent danger, warned the king that he must extinguish the fire immediately.  
16. “If not, said one prophetically, “it will never be extinguished in Ireland.  Further it would outshine all the fires we light. 
17. And he who has kindled it will conquer us all.  So the king and eight chariots full of warriors headed for Patrick’s camp.
18. Patrick responded with a simple summary of the gospel.
19. When Drochu, a leading druid, made fun of the Christian mysteries, patrick prayed aloud that he be punished.  With that, Drochu was swooped high into the air and dropped to his death.  Warriors then attempted to capture Patrick, but he prayed they would be scattered.  A dark cloud and a whirlwind descended on them, causing a panic in which many perished.  
20. The king cowred at this demonstration of might. In his fright, he made a pretense of acknowledging God and invited Patrick to speak about the Christian faith to his barons at Tara.  
21. Then he left Slane, planning to lie in wait to ambushPatrick and his associates.  
22. When Patrick and his band passed by, however, they were invisible to Laoghaire and his would-be assassins.  
23. As the Christians escaped, they chanted for the first time the saints’ famous Breastplate.  The prayer calls upon the power of the Trinity, the Incarnation, the angels, and all of heaven against every conceivable danger.
24. Patrick would prey it often.
25. Patrick showed up at King Laoghaire’s banquet at tara… but Patrick was then given a drink that Lucat-Mael, the chief druid, had laced with poison.  Discerning the mischief Patrick made a sign of the cross over the cup, and the beverage froze except for the drop of poison.  Everyone watche das Patrick poured it on the table.  He blesed the cup again, and his drink returned to normal.
26. Lucat-Mael challenged Patrick to a public contest of wonders on the plain of tara, he druid is said to have magically filled the plain with waist-high snow.  
27. We see the snow, said Patrick.  Now, remove it.
28. I cannot until tomorrow, said the druid.
29. “Then, you are powerful for evil, but not for good.  Not so with me, said Patrick.  He stretched out his hands, once again carving a cross in the air.  Instantly,  the snow disappeared without a trace.  The crowd cheered.
30. For his next magical stunt, the druid shrouded the plain in total darkness.  Once again he was unable to reverse his trick until the next day.  
31. Patrick prayed and with a blessing dismissed the darkness.  This time, the onlookers erupted with praise for Patrick’s God.
32. To settle the issue once and for all, Patrick proposed the third contenst, a trial by fire.
33. The druid, covered by Patrick’s cloak, would be locked in a ut made of freshly sawed wood.  Benignus, Patricks young disciple, would be clothe din Lucat-Mael’s cloak and placed in a hut of dry wood.  Then both huts would be burned to the ground.  
34. All accepted the terms, and with the two men in place, the huts were torched.  This test had a marvelous outcome.  Flames consumed the hut of new wood and the druid, but Patrick’s cloak was not even singed.  Benignus and his hut remained untouched by the fire, but Lucat-Maels cloak was burned to ashes.
35. Patrick’s miraculous encounters with the druids were so spectacular that modern istorians discount them as legends.  But as extraordinary as the miracles were, the earliest documents reported them as fasts.  Patrick’s wonders set the stage for the conversion of Ireland.  Why should he not have expected divine interventions at such significant moments in his missionary venture?

Even though Patrick had exposed the emptiness of Laoghaire’s religion, the ruler did not become a Christian. He made two decisions, however, that significantly advanced Patrick’s work.  He gave Patrick permission to preach the gosepl in Ireland, and he ensured Patrick’s personal safety.

From that time, Patrick crisscrossed the island, making disciples everywhere he went.  In a relatively short time, he baptized tens of thousands of converts and built hundreds of churches, staffing them with irish priests and deacons.  he founded many monasteries and schools to care fo the passionate youths who decided to follow him to Christ.  In 444, scarcely a dozen ears after Patrick arrived, he established Ireland’s first cathedral church at Armagh, which quickly became a center of Christian education and church administration.

By the time of Patrick’s death around 461, he had completely disloged the ancient paganism.  The whole island had become thoroughly and permanently Christian.  Now that’s a miracle I challenge anyone to dismiss.


Christ Is All in All

Christ with me, Christ before me,
Christ behind me, Christ within me,
Christ beneath me, Christ above me,
Christ at my right, Christ at my elft,

Christ in the head of everyone who thinks of me,
Christ in the mouth of everyone who speaks to me,
Christ in every eye that sees, me,
Christ in every ear that hears me.

- St. Patrick’s Brast plate.

