=== Tao - its history and teachings

=== By Osho

“The taoist attitude is to go with life - to go all the way,
without any conditions.  Wherever life leads, go with it.
You come form life, you are part of life, so how could life harm you?
There is no need to be afraid.”

Inner Flap:
Lao Tzu called his path “The Watercourse Way” - for man y reasons.  First, water is soft, huble, seeks the lowest place.  It may rain on Everest but the water doesn’t remain there; it starts running toward the valley.  And in the valley, too, it will reach the deepest part.  It is non-ambitious.  It has no ambitioins to be the first.  To be like water means to be utterly happy in being a nobody.  Second, water means movement.  It is always moving, and whenever it is not moving it becomes diryt, impure, even poisonous.  It dies.  Its life is in movement, in dynamism, in flow.  The whole of life is a flow, noting is stic. - Osho

Back Flap:
OSHO (1931-1990- is a contemporary mystic whose teachings have inspired millions of people from all walks of life.  his works, which are published in more than 40 languages, are transcirbed form extemporancous talks given over a period of 35 years.  They cover everythign from the individual search for happines to the most pressing social, political, and spiritual concerns of our time.  The Sunday Times of London has named Osho as one of th e”1000 Makers of the 20th Century.  His books are bestsellers in many languages and many countries.
