Taoist Wisdom

=== TAOIST WISDOM

=== Daily Teachings from the Taoist Sages
=== By Timothy Freke


THE ONENESS OF TAO 10

1. Chinese word “Tao” literally means “way.”  Tao is the way it is - the ultimate reality.
2. The Taoist sages teach that all separate things actually form a great whole.
3. This all subsuming totality is Tao.  
4. “It is what is.”
5. Tao is not a thing at all.
6. tao is a process of constant change.
7. It is the way life works. 
8. Perhaps the English word that best conveys the meaning of Tao is “Nature”.
9. Just as modern science see the ever-changing physical universe as a creation of the changeless abstract laws of Nature, so the ancient Taoist sages saw Tao as an abstract permanence that expresses itself as concrete flux.
10. Tao is the all-encompassing Nature that underlies and creates the individual natures of all things. 
11. Tao is all that exists, but it is also the nothnignness from which everything comes.
12. It is the unfolding of being from non-being.
13. Tao unites all oppsites and resolves all paradoxes.  
14. It is that which can never be comprehended by the rational mind.
15. “Tao” is an inadequate name for an impossible ideas.
16. It is a way of pointing to the ineffable Mystery.


            Mysteriously existing before Heaven and Earth.
            Silent and empty.
            An unchanging Oneness.
            An ever changing presence.
            The Mother of all Life.
            Without wishing to define it, I say it is “The Whole.”
            It is impossible to really give it a name, but I call it “Tao.”




                        Tao is the Whole,
                        The essential reality.  
                        Chuang Tzu



            Tao is like the ocean.
            All rivers run to the ocean without filling it up.
            All waters come from it without every emptying it.
            Zhun Mang
    
        
                        Tao is like an empty space that can never be filled up.
                        Yet it contains everything:
                        Blunt and sharp,
                        resolved and confused,
                        bright and dull,
                        the whole of Creation.
                        Hidden, but always present.
                        Who created it?
                        It existed before the Creator.
                        Lao Tzu




            Tao flows endlessly like water.
            It is there at the beginning and the end.
            It is wind rising,
            clouds condensing,
            thunder rumbling
            and rain falling.
            It is everything at once.
            Lao Tzu



                        Tao is like the axle of a wheel that
                        doesn’t turn itself but allows a carriage 
                        to travel thousands of miles.
                        Lao Tzu





            Tao acts like a still axis
            around which the universe evolves.
            Tai Gong Diao





                        To find the most precious of pearls doesn’t
                        compare to discovering the Source of all things.
                        Lao Tzu



YIN AND YANG
The Oneness of Tao expresses itself as a fundamental duality which the Chinese call “Yin” and “Yang”.  The dynamic relationship between Yin and Yang creates the appearance of many things from the potentiality of the Oneness.  Just as the positive and negative poles on a battery interact to create electricity, so Yin and Yang interact to create life.  Yin and ang express themselves in all opposites:  in a day and night, male and female, up and down, hot and cold, life and death, something and nothing.  Although Yin and Yang are irreconcilable opposites, they are also indivisible complementaries.   They only exist together.  They are like two ends of one piece of string.  They are conceptually separate but intrinsically connected.  It is is understanding this which enables the Taoist sages to see beyond the appearance of separate things created by Yin and Yang to the essential Oneness of Tao.



                        Yin and Yang
                        reciprocally crate, destroy, and recreate each other.
                        From their interaction comes the physical world
                        with its seasons that produce and destroy each other,
                        the human world of good and bad,
                        desirable and undesirable,
                        prosperity and adversity,
                        security and danger,
                        and the distinction between the sexes
                        with their mutual attraction for procreation.
                        Tai Gong Diao




            The union of Yin and Yang is the eternal pattern
            for the copulation of husband and wife that causes
            procreation, and the mingling of Heaven and Earth
            through which everything receives life.
            Chuang Tzu



THE BEING OF ALL BEINGS
Tao is the Oneness which appears as diversity.  It is Being
which expresses itself as all separate beings - including
ourselves.  Tao is the one Universal Self at the heart of every
individual self.  Our separate identities are only transitory 
manifestations of the one Universal Self which is our deeper
nature.  We are individual expressions of omnipresent Tao.
Individual selves live and die, but the Universal Self exists 
beyond time.  Tao has no end, because it has no beginning.
Separate individuals are like passing waves on the vast sea of 
Tao.  They rise and fall, appearing to have autonomous 
existence for a moment, and then returning to the Oneness.  But
everywhere and forever in reality there is only the ocean.


NO DOER
The fat of a wave as it rises and falls does not depend
on its free choices, but on its predetermined relationship
with the currents of the whole sea.  The taoist sages see all
individual beings like waves on the ocean of tao.  They
therefore understand that we also are not autonomous
individuals, but vehicles through which Tao expresses its
Nature.  From the enlightened perspective we are not the
doer of our actions and thinker of our thoughts, since there 
is no “you” and “I” to be a doer or a thinker.   Thoughts and
ations happen as naturally as the wind blows and the rain
falls.  This may seem to be a doctrine of passive fatalism 
which pictures us as nothing more than puppets of 
predestined fortune.  But this is to miss the deeper teachings.
Actually there are no separate individuals to be controlled
by anything.  There is only the flow of Tao.


DEATH
For the Taoist sages, death is not the end.  It is just another
change of form in the perpetually transforming tao.
Death and life are two sides of the one reality.  They are
another expression of the polarity of Yin and Yang.  Without 
death there could be no life.  Without life there would be no 
death.  They are parts of the one organic process through
which tao appears to evolve and transmutate.  Death is the
natural culmination of life which inevitably comes when it
must.  Life and death are extreme manifestations of the
everyday dialectic between continuity and change, which
creates us afresh and the same in every moment.  We are
constantly being born to the future and dying to the past, yet
we remain what we are.  What is there to fear?





            One should not consider death as a tragedy.
            Annihilation is not total.  True,, the physical self ceases to
            exist.  But the impersonal transcendent Self continues.
            Confucius.




THE NATURAL WAY
Taoism is not just about abstract metaphysics.  It offers
practical guiddance to help us awaken to tao.  taoism is the
way back to the Way.  It is sometimes called “The Natural
Way”  because it teaches us to return to our innate insticts.  It
urges us to free ourselves from the arbitrary cultural prejudices
that we have inherited from those around us and glimpse our
own essential nature.  It encourages us to be what we are, not
what we have been taught we should be.  It is by uncovering
our own genuine nature and expressing it authentically that we
become aware of the universal Nature which is Tao.






                        Social conventions lead you away
                        from the natural way of things.
                        Lieh Tzu




            The Wise are not bound by the norms of society.  Those who
            are caught up in cultural customs are inevitably constrained
            physically and drained mentally.  This is the price of allowing
            themselves to be directed from the outside.
            Lao Tzu.



                        Why not live your own life,
                        not the life that others say you should?
                        Lieh Tzu



            If you try to defy Nature you will suffer the consequences.
            Lieh Tzu




                        Hui Tzu said to Chuang Tzu, “This old tree is so crooked
                        and rough that it is useless for lumber.  In the same way, your
                        teachings have no practical use.”
                          Chuang Tzu replied, “This tree may be useless as lumber,
                        but you could rest in the gentle shade of its big branches or
                        admire its rustic character.  It only seems useless to you because
                        you want to turn it into something else and don’t know how
                        to appreciate it for what it is.  My teachings are like that.”




NATURAL GOODNESS
Tao expresses itself through its “Te.”  Te is the Natural 
Goodness of Tao, which creates and nurtures all beings.
For the Taoist sages, therefore, goodness is not something
that can be defined by any manmade moral code.  It is not
an ethical idea to be debated by philosophers.  It is the
essential nature of the universe.  Goodness is naturall innate
in each one of us.  We will not become good, therefore, by 
forcing ourselves to fit a mold created by professional 
moralizers, but by living naturally.  As long as we try to live
up to an idea of what we should be, we will always fail and
feel inadequate.  However, if we can simply be what we are,
we will live a good life, free from the unnecessary burden of 
artificial moral strictures.




            Tao follows no fixed rules. - Huai Nun Tzu



                        The Wise don’t obey useless laws - lao Tzu




            Laws are written to bring about justice.  To stick to
            the letter of a law so meticulously that it creates injustice
            is to take care of your hat and shoes while forgetting the
            head and feet they were designed to protect.
            Lao Tzu




                        An orchid doesn’t lose its fragrance
                        just because no one notices how good it smells.
                        A boat doesn’t sink
                        just because no one notices how sturdy it is.
                        The Wise don’t abandon tao
                        just because no one notices how wise they are.
                        It is their nature to be the way they are.
                        Lao Tzu






AWAKENING
the enlightened sages compare our ordinary consciousness
to a dream.  reality is found when we wake up.  this is a
gradual process of expanding our awareness.  It is a
evolution which is the essence of the lif eprocess.  It is not 
achieved by doing anything, but rather by ceasing to agitate 
the mind with restless thoughts, so that it settles down into a
state ofprimal simplicity.  when we do this, enlightenment
spontaneously happens.  We see through the veil of transitory
appearances and find ourselves in silent communion with tao.






                        A human body occupies only a little space,
                        but consciousness can reach to Heaven.
                        Chuang Tzu





            Abandon small-mindedness
            and you will avoid great delusions.
            Expand your awareness
            and you will decrase your foolishness.
            Lao Tzu





KNOWING NOTHING
Tao is not discovered through learning, but through
ignorance.  Our opinions obscure our natural intuitive
knowing.  What we think we know is just that - a thought. Tao
is what IS.  We can only know tao directly by being Tao. 
Struggling to achieve a rational
understanding of relaity is futile and will only exhaust us.  Better
to stop experiencing life via intellectual concepts, because it is
only when the mind comes to a rest that we directly perceive
the ever-present Mystery.  Only when we fully acknowledge
that we really do not know anything are we empty enough to
be filled with Tao.  Only when we understand that we can not
possibly understand will we finally understand.  Then we will
know the nothing which is Tao.







GOING WITH THE FLOW
Taoism is often interpreted as a “quietist” philosophy that
encourages us to do as little as possible  Certainly the
acncient sages teach us to avoid doing anything unnecessary
that interferes with the natural order of things, but they regard
being wilfully inactive as just as artificial and unnatural as
being too active.  the Taoist sages are not concerned about
how much we do or don’t do.  They want us to stop seeing
ourselves as autonomous doers altogether and experience life
as the unfolding of tao.  To come to this realization we must
learn to let go and go with the flow.  We must dare to willingly
follow our fate.  We must relinquish all the assumptions about
what is good and bad that cause us to struggle against the current.
We must finally abandon our futile fight to control our
lives, and let the life live us.




                        The Wise flow with Tao in life
                        and in death they merge
                        with the Oneness of things.
                        Chuang Tzu  






                        Be content with the moment
                        and be willing to follow the flow.
                        Chuang Tzu






            Those who oppose the flow of Tao
            end up being called “unlucky”.
            Lao Tzu









                    The Wise focus their attention inside.
                    They understand calamity and fortune
                    as two aspects of the Oneness.
                    Lao Tzu







            Not even the best of smiths can melt wood.
            Not even the best of carpenters can cut ice.
            When nothing can be done about the way things are,
            the Wise stop worrying about the situation.
            Lao Tzu






                        What seems favorable can be fatal.
                        What seems fatal can be favorable.
                        Lieh Tzu





            For those at one with Oneness, everything is good. 
            Taoist saying.




                        The Wise are pleased by nothing
                        and pained by nothing,
                        delighted by nothing
                        and angered by nothing.
                        Everything is mysteriously the same.
                        There is no good and bad.
                        Lao Tzu






            Nothing is wrong.  Everything is right.  - Lao Tzu



DETACHMENT
More than a thousand years after the time of Lao Tzu, the
vibrant spirit of the ancient Taoist sages was rekindled
by a new breed of Chinese masters, who synthesized Taoism 
with Indian Buddhism to produce Zen.  one such sage, Sengtsan,
 writes:  “To follow tao is easy for those that have no
preferences.”  To be able to freely follow the flow of Tao 
requires us to relinquish our attachments to things being a
certian way.  we must be impervious to loss and gain,
indifferent to praise and blame, unaffected by pleasure or
pain.  We must give up seeking wealth and fame, and accept
whatever turns out to be our lot in life.  We must allow our
desires to naturally motivate our actions, just as, for example, 
thirst causes us to search for water.  But we must not allow them
to dominate us so much that we indulge ourselves in a fruitless
attempt to control our uncontrollable lives.  We must act, but
without being attached to the results of our actions.  We must 
do what we must do and then let go.









            After enlightenment, one no longer wishes to have or
            to do anything.  When you have seen the emptiness of all
            desirs and actions, what could one wish for?
            Guan Tin Tzzu




                        Don’t worry and everything will naturally sort itself out.
                        Lao Tzu




            The Wise aren’t full of themselves.
            The more they do for others,
            the more they feel fulfilled.
            The more they give to others,
            the more t hey feel they have.
            Lao Tzu





                        Overcome unkindness with compassion.  Lao Tzu





            Day and night the Wise never forget
            their desire to help others.
            Lao Tzu
    


FOLLOWING THE WAY
Tao is the way to live in harmony with the way things are.
it is not a way that can be pointed at by someone else,
because it is not a fixed path to follow.  It is a way that each
one of us must discover for ourselves because it is a 
spontaneous expressin of our own essential nature.  All the
taoist sages can do is encourage us to listen to the inner voice
of our own heart, to enjoy the moment, and to set out on a
quest to rediscover our original simplicity.  The irony, however,
is that Tao is not a way from which we can ever deviate.  it is
reality.  We are all flowing wiht Tao whether we know it or not.
The difference between the taoist ages and the rest of us is
not that they are borne along by tao while we are splashing
about in fear of drowning; it is that we are so caught up in our
ideas about life that we do not recognize th flow of Tao
carrying us in every moment.  Sometimes, usually when life 
seems good, we may say, “I really felt as if I was with the flow 
just then.”  But at other times we do not.  When we relinquish
 the bothersome concepts of good and bad and fully enter into
life we find that Tao is not a way we have to learn to follow.
Tao is happening now and always will be.  All there is an dhas
ever been is tao - eternally present, everchanging, and ever-the-same - the unspeakable Mystery.
