

=== Title: Telepathic Human Conveys Alien Communications #4

=== Dated: July 2018

=== Transcribed Jotted-Notes and Summary


In the last few weeks some chatters seemed preoccupied with the topic of Demons and the Devil; consequently, this is the response we got when asking the Aliens through the Telepathic Human about this topic:

----

// Demons are apart of the society.
// They are actually negative energies that cause problems, pain, and anguish. 
// There is a fair amount of these negative energies.

* Hell is not a place

* Heaven is where _Prime Creator_ is

* Demons (negative energies) are sometimes made to reach the Creator to be removed.

* Angels help remove negative energies.

* Negative energies is a dark mass or negative black energy.

* Angels assist and remove the negative energies to God.

* Some humans like to create black energy with Witchcraft and Spells.

* Not good to be doing this- best to bring to creator, disperse and change.

// Prime Creator

* All my Angels are human or other races make there way up [back] to me... [It's] everyone's right and destiny to take [the] great path in life and make it here with me.  And assist me where I need them.

* So all my Angels where once walking on earth [or a] planet.  Sometimes some don't make it and become dark and [goes] in different direction.

* Don't bring it about with Witchcraft or Spells.

----

The next question had to do with is telekinesis and psychokinesis real...

----

// Mind Mind is powerful - everything has energy... Planets, hearts, minds... 
// Everything around you is energy... Yes to move objects, Yes to start fires...

* Select few people can do it and have to work on it there entire life time.  

* There not trying to stop being able to tap into unused portions of the brain [ best estimated translation ]

* Everything is Energy; Love is Energy; Put it out there and share and make a better world!

* Imagine loving energy filling the body and send it out!  

* Energy is the most amazing thing that is in everything and everywhere!

* And [ energy helps you ] come to ascension and [ get to ] the higher realm.

* We will be stronger and everyone will be telepathic!

* Don't be afraid of Aliens; they are here to help you!

* They can help you stop smoking, stop anger issues, stop depression!

* All you have to do is sit and ask the alien friends to help you quit drinking, quit drugs, or stop depression.

----

Chat User Question:  How can we connect to other dimensions?

----

// You can't now but eventually you will [ through the ] Ascension Process.
// The human mind can't handle it... ...
// You will be able to see into other dimensions and move in and out.

When? Some say 5yrs? Some say to to 100 years?

----

Continued conversation on what is an Angel...

----

// Aliens can abduct you and bring you to different planes.
// Ascension is at a higher plane - next dimension.
// [Humans] work there way up to the creator, once you make it to the Creator, you can ask to become an Angel
// [ The Angel is not a human, it was a human, gets to the creator, becomes an Angel Spirit and comes back down
// to earth to clear negative energies ]

* The Pyramids where built by higher dimensional beings.

* You got to change, got to have LOVE in your HEART, and SHARE it with the WORLD!

* LOVE your ENEMY and Be TRUE IN HEART!

* Aliens are also working on Ascension.

* If they don't have love in their hearts they won't make it!

* [From human meditation? ] There are rings around the earth- light energy that surrounds the world.

----

Chat Question:  In a video on the internet Dr. Russel Welcher talks about "Golden Triangle Head" Aliens. Is this video true? Can we talk to this Alien now?

----

* [Golden Triangle Head Alien appears to step forward and speak ] 

* [ I can't believe there calling me a Golden Triangle head said the Scientist Alien ]

* He is an 8th Dimensional being who has been around many universes assisting and helping.

* He is a highly evolved being; not directly involved but spends time in mathematics and predictive studies rather than assisting.

* He is a resource for other directions.

* He assigns directions to go on there path.

* He is the Path Finder.

----

Again, All Angels where once walking on planets.  They made it back to the Creator and became Angels to come back and help on earth.

----

// Angels scoop up the dark energies and bring them back to Prime Creator

* What is the name of the Golden Triangle Head Alien?  "BELFATH?" 8th Dimensional Being


// Chat User Asked if they would become an Angel Some Day?
// [ Could not be predicted ]

* Told he still has negative energies you need to release.  Need to build structure and maintain energy towards path.

* Think about where you want the path to go and...

* Point Arrow Energy that way... Will help you go on the appropriate path!

// Keep Love in your Heart!  The world turns with Energy.  Send Love out to the World makes a huge difference!
// Send Love to others in need!
// You can ask them (aliens) to assist you for smoking, drinking, depression.

// Focus on the Love you are sending out! 
//  Say: I can change!...
// I send you my Love to be a more loving person and
// forgive yourself and others.

----

Human Chat Question:  What do they think of earth and human beings?

----

MANTIS:  We love earth and people, you are our pride and joy!  You help us to grow!  You are our project!  We are 
here to help you!  You need to improve in the areas of pollution, fighting, anger, and Nuclear Wars.

[ You need to demonstrate ] more LOVE and PATIENCE to save the planet and save earth.

We can assist with some things.  We love you all and are here to help you.

// Continued Conversations...

* Higher density beings are more light energy - Might be a ball of light.

----

Human Chat Question:  Will I be an Angel?

----

* "I did int he past, it's done, it's over, Forgive."

----

Human Chat Question:  What is a current even we should be aware of that is happening for the humans that we can be apart of energetically?

----

Focus on No Nuclear War and it will not happen.

----

* Angels are not in human physical bodies- they are in spiritual bodies.

Human Chat Question:  On is the Universe and Illusion?

----

It's an illusion because you are not advanced enough to see the folding of the universe.

It's not an illusion anymore when you ascend you see the paths and dimensions.

* 12 - Not eating anymore 

* At some Ascension levels they still eat.

* More Advanced Levels Don't Eat.

For this Ascension you will feel more love, and love, and love.

----

Human Chat Question:  How to stay in Love with the Creator when emotions change from experience to experience?

----

You have the right to change and make it to the Creator.

Thank You Creator.

----

Human Chat Question:  Numerology?

----

* Everything is Number, Everything is Numbers.

* In Numbers are Coded

* Direction of Creation

* Certain numbers put together make a creation.

* Different numbers are different things because that is what was created.

* Everything is a number, sometimes it is a sign as well.

* As your brain matures - some people connect to that which make up everything and leads them in certain directions.

What is number 27?

* 27 is many things.  Sign of good fortune in that direction.

----

Back on the topic of Devil, Demons, and Negative Energies because some people in the chat room talk about it a lot...

----

* There is NO DEVIL!

* Only Dark Energies.

* 666 was made up.

* Angels don't have wings, it is just there energy flowing that looks like wings to humans.  Why invisible?

----

Is there anything to the Tibetan Buddha Rainbow body video on YouTube?  What it is it really?

----

* Some energies look like rainbows

* Extreme energy you see rainbow of many colors.

* They where taken to another area... Dimensional Universe.

* It's not accurate, don't be concerned with it.

----

Why was I placed on the Planet? - Asks one Chat User

----

* You chose to be here and work on evolution.

* Earth is our creation and there are many volunteers to be apart of it.

* To work toward ascension and be apart of it.

* Ascension is increasing your knowledge- Using a greater part of your brain.

* Use your energies and move through dimensions.

* You will be lighter with more energy filling your maturing brains and body.

* Everyone will get telepathy.

* You won't be talking

* You will know everything everyone is doing.

// I know you can change!  You can change!  I give you my love!
// Release negative energies.
// Aliens will assist with Alcohol, Smoking, Depression.
// Just ask I'd like the friends to remove negative energies.
// They agree to help you.

* Block bad people and bad energies.
* You can ask your angel guides for help.
* There are all different types of aliens altering the DNA for Ascension.
* Some aliens take samples of blood and do genetics, many other aliens are just watching.
* Don't be afraid - many of the aliens are scary looking.

----

* Ascension depends on Connecting to the Light!

* Most of this preparation process you do in your sleep.

* Possible in next 5 years [ but predicting time frames can be inaccurate 2023? ]

* As time goes on you will see more and understand more!

* At this time you can't understand it all.

* Keep working in the LOVE & LIGHT!!!

* More and more people will KNOW THINGS and SEE THINGS!!!

* Don't' worry if you don't understand it now - you will one day!!!


Example statement:  I am going to block all aliens that mean me harm and only ask for good aliens for assistance.  You can hold up a hand to any bad aliens and not talk to them anymore and push them away.

Bring LOVE into LIFE and FAMILY!  ENERGY is a very strong and powerful thing!  

Love those who have hurt you and those who where not kind and send Loving energy out 

It is a great honor to advance and assist others.  You must assist as they need it.  Everyone has there path to take.  To achieve... You must assist others... You will know it when you are there.






----







