
=== The Secret Doctrine
=== “The Synthesis of Science, Religion, and Philosophy.”

“The Landmark Classic of Occult Philosophy”
By H.P. Blavatsky Originally published 1888.  lived 1831-1891

“In its pages eternal mysteries are etched in ancient and modern terms, and to those who have eyes to see, the ageless wisdom is revealed.” - Manly P. Hall

“One of the most remarkable books in the world.” - Max Heindel

“There is not religion higher than truth.”


Parts of The Table of Contents that Stand Out:

Introduction  

xxv11
[“ There exists a Science called Gupta-Vidya; and that, like the once- mysterious sources of the Nile, the source of all religions and philosophies now known to the world has been for many ages forgotten and lost to men, but it at last found. “]  

The ancient Mysteries, during the performance of which the arcane doctrines were allegorically enacted…

a brief recapitulation will be made of all the principal adepts known to history, and the downfall of the mysteries will be described; after which began the disapperance and final and systematic elimination from the memory of men of the real nature of initiation and the Sacred Science…. From that time it’s teachings became Occult and Magic sailed but too often under the venerable but frequentyly misleading name of Hermetic philosophy.

As real Occultism had been prevalent among the Mystics during the centuries that preceded our era, so Magic, or rather Sorcery, with its Occult Arts, followed the beginning of Christianity…

Hoever great and zealous the fanatical efforts, during those early centuries, to obliterate every trace of the mental and intellectual labours of the Pagans….

He is acted to give all his attnetion to that millennuium which divided the pre-Christian and the post-Christian periods, by the year One of the nativity.    

“… in heaven they shall find out that there is only one true religion- the worship of God’s Spirit…”

“In other words- There is no religion (or law) higher than truth”- “SATYAT NASTI PARO DHARMAH” - the motto of the Maharajah of Benares, adopted by the Thesophical Society.

The Secret Doctrine will now throw a light on many a problem left unsolved in the first work, especially on the opening pages, which have never been understood….

“Concerned simply with the philosophies within our historical times and the respective symbolism of the fallen nations, only a hurried glance could be thrown at the panorama of Occultism in the two volumes of Isis.  

In the present work, detailed Cosmogony and the volution of the four races that preceded our Fifth race Humanity are given, and now two large volumes explain that which was stated on the first page of Isus UNveiled alone, and in a few allusions scattered hither and thither throughout the work.  

Nor could the vast catalogue of the Archaic Sciences be attempted in the present volumes, befoe we have disposed of such tremendous problems as Cosmic and Planetary Evolution, and the gradual development of the mysterious Humanities and races that preceded our “Adamic” Humanity.  

The most ancient Hebrew docuent on occult learning - “The Siphrah Dzeniouta” 
The very old book” is the original work from which the many volumes of “Kiu-ti” were compiled.

Not only SIphrah Dzeniouta but even Sepher Fezirah…..the work attributed by the Hewbrew Kabalist to their Patriarch Abraham… the book of Shu-King, CHina’s primitive bible,  the sacred volumes of the Egyptian Thoth-Hermes, the Puranas in India, and the Chaldean book of Numbers and the Pentateuch itself…are all derived from that one small parent volume.  

Tradition says, that it was taken down in Senzar, the secret sacerdotal tongue, from the words of the Divine Beings… who dictated it to the sons of Light, in Central Asia.  


There was a time when its language (the Sen-zar) was known to the Initiates of every nation, when the forefathers of the TOltec understood it as easily as the inhabitants of the lost Atlantis, who inherited it, in their turn, from the sages of the 3rd Race, the Manushis, who learnt it direct from the Devas of the 2nd and 1st Races.  

The illustration spoken of in Isis related to the evolution of these Races and of our 4th and 5th Race HUmanity in the Vaivasvata Man vantara or “Round;” 

Volume I. of “Isis” begins with a reference to “an old book”-

The old book, having described Cosmic Evolution and explained the origin of everything on earth, including physical man, after giving the true history of the races from the First down to the Fifth (our) race, goes no further.

The old book stops short at the beginning of the Kali Yuga just 3989 years ago at the death of Krishna, the bright “Sun-god” the once living hero and reformer.  

Another book, The black age, 5000 years ago…Great cycle of Kali-Yuga……

Volume II. of the Prophecies is nearly ready, having been in preparation since the time of Buddha’s grand successor, Sankaracharya.

One more important point must be noticed, one that stands foremost in the series of proofs given of the existence of one primeval, universal Wisdom- at any rate for the Christian Kabalist and students…

The teachings were, at least, partially known to severa of the Fathers of the CHurch…

Origen, Synesius, and even Clemens ALexandrinus, had been themselves initiated into the myserious before adding to the NeoPlatonism of the Alexandrian school, that of the Gnostics, under the Christian veil.

Thought by no means all- some of the doctrines of the Secret schools, were preserved in the Vatican, and have since become part of the parcel of the mysteries, Christian programme byth eLatin Church.  Such is the now materialised dogma of the Immaculate Conception.  This accounts for the great persecutions set on foot by the Roman Catholic CHurch against Occultism, Masonry, and heterodox mysticism generally.

The days of Constantine were the lat turning-point in history, the period of the Supreme struggle that ended in th eWstern world throttling the old religions in favour of the new ones, built on their bodies.  

actual existence of a Parent Doctrine.. fragments have survived geological and political cataclysms to tell the story…

The Initiates of 1888 would indeed remain incomprehensible and ever a seemingly impossible yth, were not like Initiates shown to have lived in every other age of history.  

Kali Yuga is the five pointed star reversed, thus the sign of human sorcery…. with its two points horns turned heavenward, a position every Occultist will recognize as one of the left-hand and used in ceremonial magic.

It is wrong and unjust to regard the Buddhist and Advaitee Occultists as atheists.  

Seven 


