

=== Title:  types_of_readings.adoc

=== Date: November 22, 2018

=== Source: Giordiano Berti, Mark McElroy, Barbara Monk, Tali Goodwin, Marcus Katz, Ricardo Minett and Sasha Graham. _Tarot Experience_.



"There are different types of Tarot Readings and you can make up your own formats!  For example:

* The Simple Life Story

* Expanded Life Story

* The One Year Calendar


=== Different Types of Readings

This reading is usually performed around New Years!

* Expanded Reading Example:

1. Infancy = 1 card
2. Child Hood = 1 card
3. Teenage years = 1 card
4. Each decade of life = 1 card
5. 4 Future decades = 4 cards

A life story can be a powerful and meaning gift.

Photograph of the cards and be framed as a momento to the reading experience.


* One Year calendar - A Short Story

1. 12 cards for each month of the coming year.

* Post Reading - Synthesize the Reading

1. A person wants to feel special, comfort, and assurance.  
2. Highlight the special gifts and talents and extraordinary abilities.


* Help Me - Asking more questions....

Pull extra cards for Strength that will show talents, skills and abilities.

* Action Reading

1. Leave the session with the person having a Rx in hand.  re-interpret each card as a possible recommendatino for action.

2. As ideas occur write them down.

A healthy please for helpis not a effort to transfer control or responsibility tothe reader.  When asked for, ("help me to"), identify:

Strengthes: x, y, z

Resources: x, y, z

Insights: x, y z

3. These leaves the person with action statements to help him or herself."

 
* Custom Readings

With these ideas, you can be creative and create your own custom readings.

Ideas: Sword Pattern, Dawn Pattern, Make up your own pattern.

Maybe a new purpose for the Tarot?  Inspiration? Guidance? What's the story going to say?





