=== Deciphering the Cosmic Number 

=== The Strange Friendship of Wolfgang Pauli and Caarl Jung   

=== By Arthur I. Miller 

 

----

“The extraordinary story of the psychoanalyst Carl Jung and physicist Wolfgang Pauli and their struggle to quantify the unconscious. 

Is there a number at the root of the universe? 

A primal number that everything on the universe hinges on? 

Pauli, became obsessed with the mystical power of certain numbers to explain the world. 

Pauli went to young for enlightenment and psychological validation of this quest. 

Jung, in turn, was convinced that science held the answers to some of the questions that tormented him and looked to Pauli for the physical underpinnings to his quasi-mystical theories. 

There discussion lead them to the no-man's land between Physis and Psychology of the Unconscious.  The most fascinating yet the darkest hunting ground of our time.” 

This is a dual biography tells the story of mavericks in earch of the cosmic number. 

----

 

 

 

 

 

 

 
----
 

“My brand of science, physics, has got somewhat bogged down.  The same thing can be said in different way:  “When rational methods in science reach a dead end, a new lease on life is given to those contents that were pushed out of time consciousness in the 17th century and sank into the unconscious.” - Wolfgang Pauli 

 

“Pauli had been interested not just in the rational world of physics but also the role of the irrational. 

 

Arnold Sommerfeld, his professor and lifelong mentor, was fascinated by sixteenth-century pioneer of modern science, Johannes Kepler.  
 

Science, Sommerfeld reminded his students, emerged out of mysticism and had never completely separated itself. - Arnold Sommerfeld. 


Sommerfeld also pursued kabbalistic lines of research based on pure numbers and spoke of Kepler as his precursor. 


He saw direct connection between the developments of modern science and the harmony that Kepler had been searching for. 


Pauli, too, sought out links between his work and these ancient esoteric systems of understanding the universe.   

Pauli, wrote to Sommerfeld that he had finally succeeded in using the exclusion principle to establish the reaosn why the electron shells fill up as they do in the series 2, 8, 18, 32, a grouping that SOmmerfeld had described as “somewhat kabbalistic.” 

----

 

 

_*What was so amazing about Kepler?  Pauli read Kepler’s harmonices Mundi or (Harmonics of the World).. It had an Appendix to Book V, about Robert Fludd.*_ 

 

=== Chapter *: The Dark Hunting Ground of the Mind page 124 


Pauli always liked to be well informed and, in preparation for his first meeting with Jung, had no doubt studied several of Jung’s books which he kept in his library.  He marked them in pencil: a vertical line for an important passage, two for very important, three for extremely important. 


He paid particular attention to Psychological Types,  the book in which Jung laid out the vocabulary and framework for his analytical psychology.  He indentified two poles of personality – extravert and introvert – and four “functions”, thinking versus feeling and intuition versus sensation.  Psychological Types contains by far the most markings of any of Jung’s books in his library. 

Pauli was struck by the similarity between Jung’s tug-of-war between pairs of complementary functions and bohr’s complementarity principle.   


Complementarity seemed to be everywhere.   




----

“Where the persona is intellectual, the soul is quite certainly sentimental...A very feminine woman has a masculine soul, and a very manly man a feminine soul.  This opposition is based upon the face that aman for intance, is not in all things wholly masculine, but has also certain feminine traints.” 


Jung’s description of the introverted-thinking type was an uncannily precise description of Pauli himself: 
 

“His judgment appears cold, obstinate, arbitrary, and inconsiderate; only with difficulty can he persuade himself to admit that what is clear to him may not be equally clear to everyone; [if] he falls among people who cannot understand him, he proceeds to gather further proof of the unfathomable stupidity of man; he may develop into a misanthropic bachelor with a childlike heart; he appears prickly, inaccessible haughty; [he has] a vague dread of the other sex.” 


----

 

 

=== Jungs House: 

Small office used as a retreat. 

A small desk lamp 

A rack of pigeon holes for filing papers. 

Stained-glass windows depicted mthological scenes 


Seated in his desk chair on a comfortable pillow.... Jung would smoke his pipe here while he wrote up reports and articles and replied to correspondence. 


In front of Pauli was Jung’s spacious library packed with ancient alchemical texts. 


Floor was covered with oriental rugs. 


Green-tiled stove  


Breeze blowing in from the lake kept it cool 

A writing desk with straight-backed chair and a desk lamp opposite the doorway, next to a large window looking out onto Lake Zurich. 

A couch flanked by two easy chairs occupied the opposite end of the room. 

Patients could choose either chair, depending on whether they preferred to look at the bookcase or the lake. 

Jung in 1930 – wore a full suit and tie with round spectules and pipe. 


 
=== Jung used the small room to analyze patients...

whose problems did not particulary interest him.  For those he found emotionally involving, he preferred the library. 
The larger library room gave him room for what he termed an out-of-body experience. 

On these occasions he would “go up and sit on the window, and look down and watch myself, how I am acting, until I see what from the unconscious has caught me and I can deal with it.” 

It was in the library, sitting on the couch with a table in front of him piled high with books and notes, that Dr. Jung awaited his new patient.   

Four years later, Jung described the man who came to see him that day.  Pauli was in a shockingly disintegrated state: 


----

He is highly educated person with an extraordinary development of the intellect, which was, of course, the origin of his trouble; he was just oo one-sidedly intellectual and scientific.  He was a most remakrable mind and is famous for it.  he is no ordineary person.  The reason why he consulted me was that he had completely disintegrated on account of this very one-sidedness.  It unfortunately happens that such intellectual people pay no attention to their feeling life  and so they lose contact with the world that feels, and live in a world that thinks; in a world of thoughts merely.  So in all this relations to others and to himself he had lost himself entirely. … 

----


Finally he took to drink and such nonsense and grew afraid of himself, could not understand how it happened, lost his adaptation, and was always getting into trouble.  This is the reason he made up his mind to consult me. 
 

Later, in the preface to Psyche and the Symbol, he phrased it like this: 

----

And what shall we say of a hard-boiled scientific rationalist who produced mandalas in his dreams and in his waking fantasies?  He had to consult an alienist, as he was about to lose his reason because he had suddenly become assailed by the most amazing dreams and visions. . . When the hard-boiled rationalist mentioned above came to consult me for the first time, he was in such a state of panic that not only he but I myself felt the wind blowing over from the lunatic asylum! 

----


 

=== Mandalas pg 148 

Circles appeared in Pauli’s dreams. 

Lamaistic Vajra mandala (Commentary by Jung in R. Wilhelm, The Secret of the Golden Flower (1949). 

Mandalas appear in cultures across the globe and deep into history – from Palaeolithic rock paintings, the mandalas of ancienet Egypt, and medieval mandalas with Christ at the center of the foru evangelists in the corners, to the sand paintings of the Navaho and the mandalas that play a key part in the religions of India, Tibet, and the Far East. 



=== Pauli’s first mandals:   

* In alchemy one of the ways to produce the fusion of opposites in the philosopher’s stone and the alchemical wedding is to create images. 


* To alchemists the rainbow was made up of four colors corresponding to the four Aristotelian elements – red (fire), yellow (air), green 9water) and blue (earth). 

* To create Fusion of opposites in the philosopher’s stone and the alchemical wedding is to create images. 

The philosopher's stone, more properly philosophers' stone or stone of the philosophers (Latin: lapis philosophorum) is a legendary alchemical substance capable of turning base metals such as mercury into gold (chrysopoeia, from the Greek χρυσός khrusos, "gold", and ποιεῖν poiēin, "to make") or silver. It is also called the elixir of life, useful for rejuvenation and for achieving immortality; for many centuries, it was the most sought goal in alchemy. The philosopher's stone was the central symbol of the mystical terminology of alchemy, symbolizing perfection at its finest, enlightenment, and heavenly bliss. Efforts to discover the philosopher's stone were known as the Magnum Opus ("Great Work") 


https://en.wikipedia.org/wiki/Philosopher%27s_stone 

*Pauli was well aware of the importance of the visual imagination.*

*In the1930s physics was still in a “period of spiritual and human confusion.”* 



 

 
* Guillaume’s vision: In the last canto of Les Pelerinages de l’ame (Pilgrimages of the Soul), the fourteenth-century Norman poet Guillaume de Digulleville describes a vision of a paradise made up of forty nine rotating spheres.  Guillaume’s three exuisitely illustrated allegorical poems Pilgrimage of Human life, Pilgrimage of the Soul, and Pilgrimage of Jesus Christ where to inspire John Bunyan’s Pilgrim’s Progress. .. 


* An angel informs Guillaume that these forty-nine spheres represent earthly centuries, not in ordinary time but in eternities.  A vast golden heaven surrounds all the spheres. A blue ring, a mere three feet across and half-submerged in the vast golden heaven, glides by.  So there are two intersecting systems, one vast and golden, the other small and blue. 
 

* Guillaume asks the angel why the blue circle is so much smaller than the golden circle of heaven. The angel tells him to look up and see the King and Queen of heaven o their thrones. 

* *The angel then explains to Guillaume that the small blue circle is the ecesiastical calendar and carries the element of time.* 

 

A Changed man? 
 

 

* Hung claimed that as a result of his analysis Pauli “became a perfectly normal and reasonable man” and even gave up drinking. He often spoke about the case of the intellectual young scientist as a prime example of the way in which his work on alchemical symbols had helped to shed light on the “development of symbols of the self.”  It cat light on physics, too: 


2 yrs after meeting Jung Pauli writes: 



* The specific threat to my life has been the fact that in the first half of life I swing from one extreme to the other (enantiodromia).  In the first half of my life I was a cold and cynical devil to other people and a fanatical atheist and intellectual “intrriguer.”  The opposition to that was, on the one hand, a tendency toward being a criminal, a thug (which could have degernated into me becoming a murderer), and, on the other hand being detached from the world – atotally unintellectual hermit with outbursts of ecstasy and visions. 


 
* At lake Zurich, 1920s Jung is not wearing shoes.  Rolled up sleaves and rolled up pants. (picture)



 

The ape-man... Then Pauli dreams that a monstrous ape-man is threatening him with a club.  A figure appers and drives the monster away. 

Jung shows Pauli an alchemical text written four hundreds years lieare, in which there is an image that exactly mirrors the monster in Pauli’s dream.  You see, your dream is no secret, Jung tells him.   

 

You are not the victim of a pathological insult and not separated from mankind by an inexplicable psychosis.  You are merely ignorant of certain experiences well within the bounds of human knowledge and understanding.   


 

----

There are creatures in the psyche about which we know noothing at all, says Jung.  He interprets the figure in Pauli’s dream who scares monsters away as Mephistopheles – Pauli's intelct, his rational side.  
 
Pauli has now reached a turning point in his therapy.  He has used “active imagination” to reach down into the contents of the unconscious which lie just below the level of consciousness- a method Jung developed from studying the trance states of shamans and medicine men. 

To do this Pauli has to suspend his critical faculties, to permit emotions, feelings, fantasies, obsessive thoughts, and even waking dream-images to bubble up from the unconscious. 


Jung insists that mythology- and its descendent, alchemy- requires the female element to emerge from darkness to become the fourth entity.  This will set the stage for the union of irreconcilable opposites-  mand and woman- symbolizing every primordial opposing pair, such as brother and sister. 

To illustrate this he tells a story of the Bablonian creation muth, the “Enuman Elish”... the result was a shift in the world consciousness. 

Pauli was ready to plunge into the sea of unconscious but he still feels an unberable tension between the conscious and the unconscious, rationality and irrationality. 

----

 

=== I-Ching 


The I Ching, a Chinese oracle, was written four thousands years ago.  It revealed insights into chance occurrences that cannot be understood using Western concept of causality.  . .  

The basic structure of the I CHing consists of sixty-four combinations of six broken and unbroken lines, laid out one above the other: the hexagram.  Broken lines represent yin, the feminine principle, the unbroken one, yang.  One constructs the hexagram and looks it up in the I chinag  What the oracle has to offer for any one hexagram is extremely gnomic and requires careful interpretation. 

Pauli, too, consulted the I ching for advaice “when interpreting dream siutations.  He noted that to consult the oracle one has to “draw”three times.  where as the result of the draw depends on the divisiblity of the quantity by four.   

“motif of the permeation of the 3 and the 4 was the main source of the feeling of harmony.” 

In his writing Wilhelm had disucussed the significance of “magical pictures of trees in rows”.. Relating the image to hexagram 51 – the arousing.  Shock, Tunder, in the I ching.  In this hexagram the two trigrams -  

The superior man sets his life in order 

And examines himself.   

It was a message Pauli was determined to take to heart. 

* Synchronicity: 

* Einstein symbolized his discovery that *mass- that is matter and energy were equivalent in the equation E = mc2* 

* Here solid mass is replaced by energy, which has no form. 

* Energy is indestructible and outside of time, and as a result the total quantity of energy always remains the same. This is known as the Conservation of energy. 
 
* One of the astounding results of relativity theory is that ther eis no law of conservation of mass. 

* Although energy is timeless, it appears in spac eand time in particular ways.  In quantum physics the energy of a spectral line is proportional to its frequency, that is, the numbe rof oscillations of light per time interval.   


* Frequency: number of oscillations of light per time interval. 

* There is an uncertainty relationship between energy and time. 

* Pauli laid all this out as a mandala in the shape of a cross.  From this he deduced that the laws of physics are a projection onto the psyche (the conscious/unconscious) of an archetypal association of ideas arising from the collective unconsious:  in other words, a clash of the four opposing concepts that he depicts at opposite ends of the two crosses: 


----

Indestructible energy and momentum 

 
Definite Spatio-Temporal Process 

 

Timeless Collective Unconsious ------ Self-awareness Time. 

 

The mandala lays out the fundamental complementarity at the heart of both psychology and quantum physics. 

 

In quantum physics, the person making the measurement and the measuring apparatus affect whatever is being measured.   

 

Similarly in psychology, the psychologist can never really know the unconsious through psychoanalysis.  He must always interpret the results of his questions and inevitably he himself will affect his conclusions.  Data can never be understood except through the lens of a theory. 

 

The Mysterious Number 137 

The fine structure constant:  Why 1/137? 

----

*

----

Fine structure constant had to be 1/137 

This number is one of those numbrs at the very root of the universe and of all matter. 

Max Born put it: “has the most fundamental consequences for the structure of matter in general.”   

Spectral lines are the lines that are the fingerprints of an atom... revealed when they are illuminated by light. 

The fine structure constant, in turn, is the immutable figure that defines the fine structure. 

Pauli’s mentor, Arnold Sommerfeld calculated the fine structure constant as 0.00729.... or written 1/137... known now as 137. 

Both a prime and a primal number that tickled everyone’s imagination. 

Planck’s constant and the speed of light cancel out 


Never before in the history of modern science had a pure number with no dimensions been found to play such a pivotal role.   Referred to it as the mystical number. 

----

*

=== Arthur Eddington and his mania for 137: 


1/137 or 137 the magic number. 

Bohr’s theory … 137 can be written in a series of Lucas number which are connected with Fibonacci numbers and the Golden ratio. 

Lucas numbers are like Fibonacci numbers but begin with 2:2, 1,3, 4, 7,11...  like Fibonacci serious, the Lucas series also produces the Golden Ratio. 

Fine Structure Constant seduces otherwise sane engineers and scientists into seeking mystical truths and developing far fetched theories. 


8294 appeard in Aztec and Roman texts... 

Thisnumber was a new universal consciousness... 

Also related to 666 


137 is the foundatino stone of a fiendishly complex “biblical mathematics” referred to by the followrs ot “The BIble Wheel” as a “hologrpahic generating set”.... 


Based on three geometric forms: 

A cube, A 


Divided into 27 subcubes, a hexagon B, … 


Star of david, c divied into 73 circles of course  


 

Pythagorean geometric aura 

Aficionadoes of the bible wheel... 

Claims to generate biblical pasasges and proble mystical numbers by multiplying A,B, and C in various ways.   


 


